### ISSUE TITLE
FieldRef.getFIdName() cause stackoverflow when nested fields exist.

### ISSUE THREAD

**Issue by thomassorensen** [plutext/docx4j#139]
In the latest commit  FieldRef.getFIdName() will call itself over and over until stackoverflow occurs if there is a nested field.

**Comment by cesnek** [comment]
Mee too ...

`java.lang.StackOverflowError: null

	at org.docx4j.model.fields.FieldRef.getFldName(FieldRef.java:300) ~[docx4j-3.3.5.jar:na]
	at org.docx4j.model.fields.FieldRef.getFldName(FieldRef.java:304) ~[docx4j-3.3.5.jar:na]
	at org.docx4j.model.fields.FieldRef.getFldName(FieldRef.java:304) ~[docx4j-3.3.5.jar:na]
	at org.docx4j.model.fields.FieldRef.getFldName(FieldRef.java:304) ~[docx4j-3.3.5.jar:na]
	at org.docx4j.model.fields.FieldRef.getFldName(FieldRef.java:304) ~[docx4j-3.3.5.jar:na]
	at org.docx4j.model.fields.FieldRef.getFldName(FieldRef.java:304) ~[docx4j-3.3.5.jar:na]`

**Comment by wussup** [comment]
And me too...

Example (if statement have nested field):

IF "«field»" = "1" "something" "else"

> java.lang.StackOverflowError: null
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:449)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at ch.qos.logback.core.pattern.FormattingConverter.write(FormattingConverter.java:39)
	at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:115)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:141)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:39)
	at ch.qos.logback.core.encoder.LayoutWrappingEncoder.encode(LayoutWrappingEncoder.java:115)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:230)
	at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:235)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.error(Logger.java:522)
	at org.docx4j.model.fields.FieldRef.getFldName(FieldRef.java:300)
	at org.docx4j.model.fields.FieldRef.getFldName(FieldRef.java:304)
	at org.docx4j.model.fields.FieldRef.getFldName(FieldRef.java:304)
	at org.docx4j.model.fields.FieldRef.getFldName(FieldRef.java:304)
	at org.docx4j.model.fields.FieldRef.getFldName(FieldRef.java:304)

**Comment by kerner1000** [comment]
Still not fixed..
Is there a way to update the properties specifically? To avoid the FileUpdater traverse through the whole document?
