### ISSUE TITLE
Document cannot be parsed when converted from pdf to docx using Word 2003

### ISSUE THREAD

**Issue by jstroleny** [plutext/docx4j#146]
When user converts pdf to docx using Word 2003 (saved as docx) then document cannot be parsed, because there is invalid value in document.xml that do not correspond to schema during unmarshalling. 

See following snippet from *document.xml* that causes problems (see **miterlimit** attribute that is defined as BigDecimal in **CTStroke.java**, but value is **"83231f"** that cannot be parsed as BigDecimal):
```
<w:pict>
<v:group ... truncated...>
<v:shape ...truncated...>
<v:stroke miterlimit="83231f" joinstyle="miter"/>
<v:path arrowok="t" textboxrect="0,0,5981713,9144"/>
</v:shape>
<w10:anchorlock/>
</v:group>
</w:pict>
```

When this document is parsed using docx4j then following exception occurs:
```
Caused by: java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:470)
	at java.math.BigDecimal.<init>(BigDecimal.java:739)
	at com.sun.xml.internal.bind.DatatypeConverterImpl._parseDecimal(DatatypeConverterImpl.java:132)
	at com.sun.xml.internal.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$22.parse(RuntimeBuiltinLeafInfoImpl.java:778)
	at com.sun.xml.internal.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$22.parse(RuntimeBuiltinLeafInfoImpl.java:776)
	at com.sun.xml.internal.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.parse(TransducedAccessor.java:230)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:194)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.ProxyLoader.startElement(ProxyLoader.java:45)
	at com.sun.xml.internal.bind.v2.runtime.ElementBeanInfoImpl$IntercepterLoader.startElement(ElementBeanInfoImpl.java:238)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.ProxyLoader.startElement(ProxyLoader.java:45)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:486)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:465)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:60)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:135)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:229)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:266)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:235)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:266)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:235)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:266)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:235)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:266)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:235)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:266)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:235)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:266)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:235)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:266)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:235)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:112)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:95)
	at com.sun.xml.internal.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:88)
	at com.sun.xml.internal.bind.v2.runtime.BinderImpl.associativeUnmarshal(BinderImpl.java:146)
	at com.sun.xml.internal.bind.v2.runtime.BinderImpl.unmarshal(BinderImpl.java:117)
	at org.docx4j.openpackaging.parts.WordprocessingML.MainDocumentPart.unmarshal(MainDocumentPart.java:252)
	... 67 more
```

I can provide you example document, if needed.

**Comment by plutext** [comment]
You mean Word 2013, right?

Please do provide a sample docx.

**Comment by jstroleny** [comment]
When saved using Word 2013 into docx then this document cannot be parsed using docx4j library.

See following example document: [DPP-77385-Sample.docx](https://drive.google.com/file/d/0B_e7YGgwMRWPZGN6Y1JmWWtJQ1k/view?usp=sharing)

**Comment by plutext** [comment]
Although it is defined in the ECMA 376 4ed VML schema as

<xsd:attribute name="miterlimit" type="xsd:decimal" use="optional"/>

Microsoft sometimes uses a string:  https://technet.microsoft.com/en-us/library/documentformat.openxml.vml.stroke.miterlimit.aspx

I've modified docx4j to match with https://github.com/plutext/docx4j/commit/1a5e25a987e807be536173e891813dc8e3ab2186

Alternatively (or additionally) a fix could be added to mc-preprocessor.xslt
