### ISSUE TITLE
Didn't find class "org.apache.log4j.Logger" on path

### ISSUE THREAD

**Issue by Shvet** [plutext/docx4j#180]
I am using ANdroid studio where i am reading docx file from sd card. but it is giving me error.

```
[02-16 17:06:33.572 23635-23635/com.shvet.pdfreaders E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.shvet.pdfreaders, PID: 23635
                                                                      java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/log4j/Logger;
                                                                          at org.docx4j.convert.in.Doc.<clinit>(Doc.java:45)
                                                                          at com.shvet.pdfreaders.fragments.PdfViewFragment$6.fileSelected(PdfViewFragment.java:207)
                                                                          at com.shvet.pdfreaders.extra.FileChooser$1.onItemClick(FileChooser.java:59)
                                                                          at android.widget.AdapterView.performItemClick(AdapterView.java:305)
                                                                          at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
                                                                          at android.widget.AbsListView$PerformClick.run(AbsListView.java:3057)
                                                                          at android.widget.AbsListView$3.run(AbsListView.java:3864)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:139)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5298)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.log4j.Logger" on path: DexPathList[[zip file "/data/app/com.shvet.pdfreaders-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                          at org.docx4j.convert.in.Doc.<clinit>(Doc.java:45) 
                                                                          at com.shvet.pdfreaders.fragments.PdfViewFragment$6.fileSelected(PdfViewFragment.java:207) 
                                                                          at com.shvet.pdfreaders.extra.FileChooser$1.onItemClick(FileChooser.java:59) 
                                                                          at android.widget.AdapterView.performItemClick(AdapterView.java:305) 
                                                                          at android.widget.AbsListView.performItemClick(AbsListView.java:1146) 
                                                                          at android.widget.AbsListView$PerformClick.run(AbsListView.java:3057) 
                                                                          at android.widget.AbsListView$3.run(AbsListView.java:3864) 
                                                                          at android.os.Handler.handleCallback(Handler.java:739) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                          at android.os.Looper.loop(Looper.java:139) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5298) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
                                                                      	Suppressed: java.lang.ClassNotFoundException: org.apache.log4j.Logger
                                                                          at java.lang.Class.classForName(Native Method)
                                                                          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                          at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                          		... 16 more
                                                                       Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
](url)
```

**build.gradle**

apply plugin: 'com.android.application'

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.shvet.pdfreaders"
        minSdkVersion 11
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dexOptions {
        incremental true
        javaMaxHeapSize "4g"
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:cardview-v7:23.1.1'
    compile('org.docx4j:docx4j:2.8.0') {
        transitive = false
        exclude group: 'org.apache.logging.log4j'
        exclude module: 'org.apache.logging.log4j'
    }
    compile 'org.apache.logging.log4j:log4j-core:2.5'
//    compile files('libs/docx4j-2.8.0.jar')
}
```

**Comment by Shvet** [comment]
I have solved the problem with few changes in gradle file.
