### ISSUE TITLE
NullPointerException at org.docx4j.XmlUtils.replace(XmlUtils.java:520)

### ISSUE THREAD

**Issue by Caltalys** [plutext/docx4j#201]
```
java.lang.NullPointerException
	at org.docx4j.XmlUtils.replace(XmlUtils.java:520)
	at org.docx4j.XmlUtils.replace(XmlUtils.java:527)
	at org.docx4j.XmlUtils.replace(XmlUtils.java:527)
	at org.docx4j.XmlUtils.replace(XmlUtils.java:527)
	at org.docx4j.XmlUtils.unmarshallFromTemplate(XmlUtils.java:498)
	at org.docx4j.openpackaging.parts.JaxbXmlPart.variableReplace(JaxbXmlPart.java:264)
	at vn.toancauxanh.xdcb.model.ExportBaoCaoWord.variableReplace(ExportBaoCaoWord.java:157)
```

my code, ExportBaoCaoWord.java:157: 

`getWordMLPackage().getMainDocumentPart().variableReplace(mappings);`

I've already check null both WordMLPackage, MainDocumentPart and in every entry of the mapping value and there is no null.

**Comment by plutext** [comment]
See https://github.com/plutext/docx4j/issues/200
