### ISSUE TITLE
XMLUtils:deepCopy is broken (at least with MOXy)

### ISSUE THREAD

**Issue by pwilkin** [plutext/docx4j#212]
In the old deepCopy code, there was a special provision for when the copied element was a JAXBElement. The new code doesn't have that, so whenever it encounters a JAXBElement, MOXy throws the following error: 

```
Exception [EclipseLink-25007] (Eclipse Persistence Services - 2.6.3.v20160428-59c81c5): org.eclipse.persistence.exceptions.XMLMarshalException
Exception Description: A descriptor for class javax.xml.bind.JAXBElement was not found in the project.  For JAXB, if the JAXBContext was bootstrapped using TypeMappingInfo[] you must call a marshal method that accepts TypeMappingInfo as an input parameter.
	at org.eclipse.persistence.exceptions.XMLMarshalException.descriptorNotFoundInProject(XMLMarshalException.java:154)
	at org.eclipse.persistence.internal.oxm.Context$ContextState.getSession(Context.java:137)
	at org.eclipse.persistence.oxm.XMLContext$XMLContextState.getSession(XMLContext.java:798)
	at org.eclipse.persistence.oxm.XMLContext$XMLContextState.getSession(XMLContext.java:1)
	at org.eclipse.persistence.internal.oxm.Context.getSession(Context.java:458)
	at org.eclipse.persistence.oxm.XMLContext.getSession(XMLContext.java:366)
	at org.eclipse.persistence.oxm.XMLContext.getSession(XMLContext.java:1)
	at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:493)
	at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:731)
	at org.eclipse.persistence.internal.oxm.XMLUnmarshaller.unmarshal(XMLUnmarshaller.java:649)
	at org.eclipse.persistence.jaxb.JAXBUnmarshaller.unmarshal(JAXBUnmarshaller.java:349)
	at org.docx4j.XmlUtils.deepCopy(XmlUtils.java:794)
	at org.docx4j.XmlUtils.deepCopy(XmlUtils.java:774)
```

**Comment by pwilkin** [comment]
By contrast, the old deepCopy code (from docx4j 3.0.0) works fine.

**Comment by plutext** [comment]
Thanks for this.

This issue follows https://github.com/plutext/docx4j/pull/163

In looking to resolve this, I just posted http://stackoverflow.com/questions/39069943/moxy-efficient-deep-copy-of-jaxbelement

**Comment by plutext** [comment]
Broken with Sun/Oracle implementation as well.
Fixed by https://github.com/plutext/docx4j/commit/b5d8b4722e814945e502da9f0516d59c498b64bb
