### ISSUE TITLE
How to set "PP_APACHEFOP_DISABLE_PAGEBREAK_LIST_ITEM"?

### ISSUE THREAD

**Issue by izhangzhihao** [plutext/docx4j#218]
I get this error ：
org.docx4j.openpackaging.exceptions.Docx4JException: Exception exporting package

	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:109)
	at org.docx4j.Docx4J.toFO(Docx4J.java:568)
	at com.github.izhangzhihao.OfficeUtils.DocxProducer.convertDocxToPDF(DocxProducer.java:162)
	at com.github.izhangzhihao.OfficeUtils.DocxProducer.CreateFromTemplate(DocxProducer.java:52)
	at com.github.izhangzhihao.OfficeUtils.test.testset(test.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.docx4j.openpackaging.exceptions.Docx4JException: Missing WordprocessingMLPackage in the conversion settings
	at org.docx4j.convert.out.common.AbstractWmlExporter.preprocess(AbstractWmlExporter.java:49)
	at org.docx4j.convert.out.common.AbstractWmlExporter.preprocess(AbstractWmlExporter.java:32)
	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:64)
	... 31 more

and I found "throw new Docx4JException("Exception exporting package; FOP https://issues.apache.org/bugzilla/show_bug.cgi?id=54094 .. try PP_APACHEFOP_DISABLE_PAGEBREAK_LIST_ITEM",e);"

thanks for your help.

**Comment by izhangzhihao** [comment]
now I make this ：
``` java
        HashSet<String> features = new HashSet<>();
        features.add(PP_PDF_APACHEFOP_DISABLE_PAGEBREAK_LIST_ITEM);
        WordprocessingMLPackage process = Preprocess.process(wordMLPackage, features);
        Docx4J.toPDF(process, new java.io.FileOutputStream(pdfPath));
```

and I get this ：
```

org.docx4j.openpackaging.exceptions.Docx4JException: Exception exporting package

	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:105)
	at org.docx4j.Docx4J.toFO(Docx4J.java:568)
	at org.docx4j.Docx4J.toPDF(Docx4J.java:583)
	at com.github.izhangzhihao.OfficeUtils.DocxProducer.convertDocxToPDF(DocxProducer.java:168)
	at com.github.izhangzhihao.OfficeUtils.DocxProducer.CreateFromTemplate(DocxProducer.java:54)
	at com.github.izhangzhihao.OfficeUtils.test.testset(test.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at org.apache.fop.fonts.FontCache.addFont(FontCache.java:335)
	at org.apache.fop.fonts.DefaultFontConfigurator.getFontInfo(DefaultFontConfigurator.java:173)
	at org.apache.fop.fonts.DefaultFontConfigurator.addFonts(DefaultFontConfigurator.java:136)
	at org.apache.fop.fonts.DefaultFontConfigurator.configure(DefaultFontConfigurator.java:89)
	at org.apache.fop.render.PrintRendererConfigurator.getCustomFontCollection(PrintRendererConfigurator.java:147)
	at org.apache.fop.render.PrintRendererConfigurator.setupFontInfo(PrintRendererConfigurator.java:127)
	at org.apache.fop.render.intermediate.IFUtil.setupFonts(IFUtil.java:170)
	at org.apache.fop.render.intermediate.IFRenderer.setupFontInfo(IFRenderer.java:187)
	at org.apache.fop.area.RenderPagesModel.<init>(RenderPagesModel.java:75)
	at org.apache.fop.area.AreaTreeHandler.setupModel(AreaTreeHandler.java:135)
	at org.apache.fop.area.AreaTreeHandler.<init>(AreaTreeHandler.java:105)
	at org.apache.fop.render.RendererFactory.createFOEventHandler(RendererFactory.java:350)
	at org.apache.fop.fo.FOTreeBuilder.<init>(FOTreeBuilder.java:107)
	at org.apache.fop.apps.Fop.createDefaultHandler(Fop.java:104)
	at org.apache.fop.apps.Fop.<init>(Fop.java:78)
	at org.apache.fop.apps.FOUserAgent.newFop(FOUserAgent.java:182)
	at org.apache.fop.apps.FopFactory.newFop(FopFactory.java:220)
	at org.docx4j.convert.out.fo.renderers.FORendererApacheFOP.render(FORendererApacheFOP.java:199)
	at org.docx4j.convert.out.fo.renderers.FORendererApacheFOP.render(FORendererApacheFOP.java:159)
	at org.docx4j.convert.out.fo.AbstractFOExporter.postprocess(AbstractFOExporter.java:168)
	at org.docx4j.convert.out.fo.AbstractFOExporter.postprocess(AbstractFOExporter.java:47)
	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:82)
	... 32 more
```
