### ISSUE TITLE
Error with name space parsing on bind going from 3.3.0 to 3.3.2

### ISSUE THREAD

**Issue by roytmana** [plutext/docx4j#230]
This is XML being injected
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:case xmlns:ns2="http://gctrack.gao.gov/templates/case-data">
    <documentId>118905</documentId>
    <fileNumber>408694</fileNumber>
    <caseNumber>9</caseNumber>
```

this  is the snippet of code
```java
// xmlDocument is created by JAXB marshalling  of my data class to Document 
//created using docx4j org.docx4j.XmlUtils#neww3cDomDocument

wordMLPackage = Docx4J.load(new File(targetPath, "case-data-elements-inventory.docx"));
Docx4J.bind(wordMLPackage, xmlDocument, Docx4J.FLAG_BIND_INSERT_XML + 
Docx4J.FLAG_BIND_BIND_XML + Docx4J.FLAG_BIND_REMOVE_SDT);
```
Here is th eexception in 3.3.2 which I did not have in 3.3.0

```
Exception in thread "main" org.docx4j.openpackaging.exceptions.Docx4JException: Problems applying bindings
	at org.docx4j.model.datastorage.BindingTraverserXSLT.traverseToBind(BindingTraverserXSLT.java:188)
	at org.docx4j.model.datastorage.BindingHandler.applyBindings(BindingHandler.java:259)
	at org.docx4j.model.datastorage.BindingHandler.applyBindings(BindingHandler.java:189)
	at org.docx4j.Docx4J.bind(Docx4J.java:433)
	at peacetech.gao.ogc.gctrack.test.TestAddCustomXmlPart.main(TestAddCustomXmlPart.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:143)
Caused by: java.lang.IllegalArgumentException: Unexpected localName ns2:case
	at org.docx4j.model.datastorage.xpathtracker.Histgram.update(Histgram.java:29)
	at org.docx4j.model.datastorage.DomToXPathMap.walkTree(DomToXPathMap.java:67)
	at org.docx4j.model.datastorage.DomToXPathMap.walkTree(DomToXPathMap.java:61)
	at org.docx4j.model.datastorage.DomToXPathMap.map(DomToXPathMap.java:35)
	at org.docx4j.model.datastorage.BindingTraverserXSLT.traverseToBind(BindingTraverserXSLT.java:162)
	... 9 more
```

**Comment by roytmana** [comment]
i think it is related to 0d7f35319726b3d302ae319303c9cb149609999a

**Comment by roytmana** [comment]
I am not sure why you are pulling qname with getNodeName() but then throw an exception if it has namespace part. If  you have to do it because of some case of node creation lacking local name I would do something like this
```java
sourceNode.getLocalName() == null ? sourceNode.getNodeName() : sourceNode.getLocalName()/* not getLocalName, which returns null if the element was created using createElement() */,
```

**Comment by plutext** [comment]
Yeah, might have to do something like that.  But since behaviour seems to differ across parsers, first I'd like to understand that a bit more, and ideally, construct a unit test.

Could you please try http://www.docx4java.org/docx4j/docx4j-nightly-20170112.jar
and copy the log output from org.docx4j.model.datastorage.DomToXPathMap

That contains:

`catch (java.lang.IllegalArgumentException iae) {`
            	
            		log.error(sourceNode.getClass().getName());
            		log.error("sourceNode.getNodeName(): " + sourceNode.getNodeName());
            		log.error("sourceNode.getNamespaceURI(): " + sourceNode.getNamespaceURI());
            		log.error("sourceNode.getLocalName(): " + sourceNode.getLocalName());
            		log.error("sourceNode.getPrefix(): " + sourceNode.getPrefix());
            		log.error("java.vendor="+System.getProperty("java.vendor"));
            		log.error("java.version="+System.getProperty("java.version"));
            		
            		throw iae;            		
            	}

Thanks.

**Comment by roytmana** [comment]
```
DEBUG 11/01/17 20:43:09 datastorage.DomToXPathMap - child 0of DOCUMENT_NODE
ERROR 11/01/17 20:43:09 xpathtracker.Histgram - Unexpected localName ns2:case
ERROR 11/01/17 20:43:09 datastorage.DomToXPathMap - com.sun.org.apache.xerces.internal.dom.ElementNSImpl
ERROR 11/01/17 20:43:09 datastorage.DomToXPathMap - sourceNode.getNodeName(): ns2:case
ERROR 11/01/17 20:43:09 datastorage.DomToXPathMap - sourceNode.getNamespaceURI(): http://gctrack.gao.gov/templates/case-data
ERROR 11/01/17 20:43:09 datastorage.DomToXPathMap - sourceNode.getLocalName(): case
ERROR 11/01/17 20:43:09 datastorage.DomToXPathMap - sourceNode.getPrefix(): ns2
ERROR 11/01/17 20:43:09 datastorage.DomToXPathMap - java.vendor=Oracle Corporation
ERROR 11/01/17 20:43:09 datastorage.DomToXPathMap - java.version=1.8.0_111

```
