### ISSUE TITLE
Can not convert #STRING to a NodeList!

### ISSUE THREAD

**Issue by ThomBi** [plutext/docx4j#234]
Hi,

for xpath expressions returning strings the following exception occurs.
We are using docx4j v3.3.3, but I think the problem was introduced in v3.3.1.
XmlPart.java already contains code dealing with #BOOLEAN and #NUMBER but not #STRING.

Stacktrace:
15:25:52,359 ERROR  [Logger.error:408] #STRING kann nicht in NodeList konvertiert werden!
15:25:52,359 ERROR  [Logger.error:408] Handle XPath of form: concat('- als ', /header/priceType, ' -')
15:25:52,359 ERROR  [Logger.error:408] Oracle Corporation
15:25:52,360 ERROR  [Logger.error:408] 1.8.0_121
15:25:52,360 ERROR  [Logger.error:408] de_DE
15:25:52,361 ERROR  [Logger.error:419] Exception executing concat('- als ', /header/priceType, ' -')
org.docx4j.openpackaging.exceptions.Docx4JException: Exception executing concat('- als ', /header/priceType, ' -')
	at org.docx4j.openpackaging.parts.XmlPart.cachedXPathGetString(XmlPart.java:334)
	at org.docx4j.openpackaging.parts.CustomXmlDataStoragePart.cachedXPathGetString(CustomXmlDataStoragePart.java:169)
	at org.docx4j.model.datastorage.BindingHandler.xpathGetString(BindingHandler.java:323)
	at org.docx4j.model.datastorage.BindingTraverserXSLT.xpathGenerateRuns(BindingTraverserXSLT.java:925)

Thanks,
T.

**Comment by plutext** [comment]
Please try http://www.docx4java.org/docx4j/docx4j-nightly-20170228.jar
