### ISSUE TITLE
 Can't construct org.docx4j.openpackaging.parts.WordprocessingML.ImageBmpPart

### ISSUE THREAD

**Issue by chilejiang1024** [plutext/docx4j#238]
- Here is the log 
```
2017-03-20 11:31:27,890 [main] ERROR [com.plutext.merge.CopyGeneric] - Can't construct org.docx4j.openpackaging.parts.WordprocessingML.ImageBmpPart
2017-03-20 11:31:27,890 [main] WARN  [com.plutext.merge.CopyGeneric] - org.docx4j.openpackaging.parts.WordprocessingML.ImageBmpPart
```

- Here is the exception
```
Exception in thread "main" java.lang.ClassCastException: org.docx4j.openpackaging.parts.WordprocessingML.BinaryPart cannot be cast to org.docx4j.openpackaging.parts.WordprocessingML.BinaryPartAbstractImage
	at com.plutext.merge.ImageCopier.manageImageCopy(ImageCopier.java:100)
	at com.plutext.merge.DocumentBuilder.copyImages(DocumentBuilder.java:2869)
	at com.plutext.merge.DocumentBuilder.copyReferences(DocumentBuilder.java:1525)
	at com.plutext.merge.DocumentBuilder.appendDocument(DocumentBuilder.java:1075)
	at com.plutext.merge.DocumentBuilder.buildDocument(DocumentBuilder.java:473)
	at com.plutext.merge.DocumentBuilder.buildOpenDocument(DocumentBuilder.java:273)
```

- Here is the situation
When I tried to merge 2 docx files that only contains a bmp image, Docx4J give a exception ....
Is there a solution???

**Comment by plutext** [comment]
Thanks for this; this is fixed in https://www.plutext.com/dn/downloads/1490093872822/Plutext-Enterprise-3.3.0.9-trial.zip

**Comment by dingmingyue007** [comment]
I also encountered this problem, how can  solved it？

**Comment by plutext** [comment]
What document(s) and code caused this problem for you?  What versions are you running?

**Comment by dingmingyue007** [comment]
> What document(s) and code caused this problem for you? What versions are you running?
My problem is that two word documents are merged. If there is a picture in bmp format in one document, it will be abnormal. The class is CopyGeneric.class.
```
` try {
            if (inputPart instanceof AlternativeFormatInputPart) {
                newPart = new AlternativeFormatInputPart(existingName);
                ((BinaryPart)newPart).setContentType(new ContentType(inputPart.getContentType()));
            } else if (inputPart instanceof ImageEpsPart) {
                newPart = new ImageEpsPart(existingName);
            } else if (inputPart instanceof ImageGifPart) {
                newPart = new ImageGifPart(existingName);
            } else if (inputPart instanceof ImageJpegPart) {
                newPart = new ImageJpegPart(existingName);
            } else if (inputPart instanceof ImagePngPart) {
                newPart = new ImagePngPart(existingName);
            } else if (inputPart instanceof ImageTiffPart) {
                newPart = new ImageTiffPart(existingName);
            } else if (inputPart instanceof ObfuscatedFontPart) {
                newPart = new ObfuscatedFontPart(existingName);
            } else if (inputPart instanceof MetafileEmfPart) {
                newPart = new MetafileEmfPart(existingName);
            } else if (inputPart instanceof MetafileWmfPart) {
                newPart = new MetafileWmfPart(existingName);
            } else if (inputPart.getClass().getName().equals("org.docx4j.openpackaging.parts.WordprocessingML.BinaryPart")) {
                newPart = new BinaryPart(existingName);
                ((BinaryPart)newPart).setContentType(new ContentType(inputPart.getContentType()));
                ((BinaryPart)newPart).setRelationshipType(inputPart.getRelationshipType());
            } else {
                newPart = (BinaryPart)inputPart.getClass().newInstance();
                ((BinaryPart)newPart).setContentType(new ContentType(inputPart.getContentType()));
                ((BinaryPart)newPart).setRelationshipType(inputPart.getRelationshipType());
            }
        } catch (Exception var8) {
            log.error("Can't construct " + inputPart.getClass().getName());
            log.warn(var8.getMessage());
            log.info("trying to recover from that..");

            try {
                newPart = new BinaryPart(existingName);
                ((BinaryPart)newPart).setContentType(new ContentType(inputPart.getContentType()));
                ((BinaryPart)newPart).setRelationshipType(inputPart.getRelationshipType());
                log.info("ok, fell back to new binary part ..");
            } catch (InvalidFormatException var7) {
                log.error(var7.getMessage(), var7);
            }
        }`
```

**Comment by dingmingyue007** [comment]
This should be a bug. 
` newPart = new BinaryPart(existingName);
 BinaryPartAbstractImage newPart = (BinaryPartAbstractImage)CopyGeneric.cloneBinaryPart(migratingPart);`
Is this allowed？

**Comment by plutext** [comment]
Where did you get that old code?    I've tested merging documents containing bmp using our current version; works fine.  For Enterprise support, please contact support@plutext.com
