### ISSUE TITLE
Exception exporting package

### ISSUE THREAD

**Issue by sooryakp** [plutext/docx4j#251]
I got this error....

org.docx4j.openpackaging.exceptions.Docx4JException: Exception exporting package
	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:105)
	at org.docx4j.Docx4J.toHTML(Docx4J.java:666)
	at org.docx2html.service.DocXToHtml.convert(DocXToHtml.java:106)
	at org.controller.action.FileInputAction.doPost(FileInputAction.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Can't clone a null argument
	at org.docx4j.XmlUtils.deepCopy(XmlUtils.java:953)
	at org.docx4j.convert.out.common.preprocess.PartialDeepCopy.deepCopyContent(PartialDeepCopy.java:245)
	at org.docx4j.convert.out.common.preprocess.PartialDeepCopy.copyPart(PartialDeepCopy.java:229)
	at org.docx4j.convert.out.common.preprocess.PartialDeepCopy.deepCopyPart(PartialDeepCopy.java:205)
	at org.docx4j.convert.out.common.preprocess.PartialDeepCopy.deepCopyRelationships(PartialDeepCopy.java:190)
	at org.docx4j.convert.out.common.preprocess.PartialDeepCopy.process(PartialDeepCopy.java:80)
	at org.docx4j.convert.out.common.Preprocess.process(Preprocess.java:77)
	at org.docx4j.convert.out.common.Preprocess.process(Preprocess.java:135)
	at org.docx4j.convert.out.common.AbstractWmlExporter.preprocess(AbstractWmlExporter.java:51)
	at org.docx4j.convert.out.common.AbstractWmlExporter.preprocess(AbstractWmlExporter.java:1)
	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:64)
	... 27 more
Jun 16, 2017 1:45:10 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [FileInputAction] in context with path [/wordToHtml] threw exception

**Comment by plutext** [comment]
can you save the docx before exporting to HTML?

if you load this docx, then export, does it work?

if not, please attach

**Comment by SelvaSurukam** [comment]
Hi Thanks for the quick reply.

We are using this sample code for converting `docx` to `html` this point of line https://github.com/plutext/docx4j/blob/master/src/samples/docx4j/org/docx4j/samples/ConvertOutHtml.java#L148

We are getting error like below.

```
Exception in thread "main" org.docx4j.openpackaging.exceptions.Docx4JException: Exception exporting package
	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:105)
	at org.docx4j.Docx4J.toHTML(Docx4J.java:673)
	at org.docx4j.samples.ConvertOutHtml.main(ConvertOutHtml.java:153)
Caused by: java.lang.IllegalArgumentException: Can't clone a null argument
	at org.docx4j.XmlUtils.deepCopy(XmlUtils.java:1028)
	at org.docx4j.convert.out.common.preprocess.PartialDeepCopy.deepCopyContent(PartialDeepCopy.java:245)
	at org.docx4j.convert.out.common.preprocess.PartialDeepCopy.copyPart(PartialDeepCopy.java:229)
	at org.docx4j.convert.out.common.preprocess.PartialDeepCopy.deepCopyPart(PartialDeepCopy.java:205)
	at org.docx4j.convert.out.common.preprocess.PartialDeepCopy.deepCopyRelationships(PartialDeepCopy.java:190)
	at org.docx4j.convert.out.common.preprocess.PartialDeepCopy.process(PartialDeepCopy.java:80)
	at org.docx4j.convert.out.common.Preprocess.process(Preprocess.java:77)
	at org.docx4j.convert.out.common.Preprocess.process(Preprocess.java:135)
	at org.docx4j.convert.out.common.AbstractWmlExporter.preprocess(AbstractWmlExporter.java:51)
	at org.docx4j.convert.out.common.AbstractWmlExporter.preprocess(AbstractWmlExporter.java:1)
	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:64)
	... 2 more
```
Please find Sample [Document.docx](https://github.com/plutext/docx4j/files/1080242/LawInsiderContract1B1AGXc8flyh7JMKaKuxiv.docx)

**Comment by SelvaSurukam** [comment]
Let us know whether this issue is quick fix or not ? which will helpful to take decision on our development plan.

**Comment by plutext** [comment]
You are ignoring the errors:

WARN org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware .unmarshal line 479 - For input string: "9360.000"
java.lang.NumberFormatException: For input string: "9360.000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)

caused by this in your document:
   <w:tblW w:w="9360.000000000002"

and 

java.lang.NumberFormatException: For input string: "391.1081"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)

caused by <w:gridCol w:w="391.1081397292328"/> etc.

You need to fix your docx.   What app was it created in?

**Comment by sooryakp** [comment]
Hi,
Thanks for the response.
The document is actually downloaded from some website. I think there is not much to do with the document fixing. How we can go for the second option.?

**Comment by plutext** [comment]
https://github.com/plutext/docx4j/commit/b6175b8b8390a2e589cefa33d1cac51ee0e24c54

**Comment by SelvaSurukam** [comment]
@plutext nice thanks for the quick resolution.
