### ISSUE TITLE
docx4j nullPointerException on webshere 

### ISSUE THREAD

**Issue by nevzatbayar** [plutext/docx4j#261]
This works on local but doesnt work on server(Webshere 8.5.5.11) . I use Eclipse IDE. Can anyone tell me why I get this error?

[14.09.2017 10:55:22:785 EET] 00000112 XmlUtils      W org.docx4j.XmlUtils <clinit> default SAXParserFactory property : null
 Please consider using Xerces.
[14.09.2017 10:55:22:786 EET] 00000112 XmlUtils      I org.docx4j.XmlUtils <clinit> actual: org.apache.xerces.jaxp.SAXParserFactoryImpl
[14.09.2017 10:55:22:786 EET] 00000112 XmlUtils      W org.docx4j.XmlUtils <clinit> default DocumentBuilderFactory property: null
 Please consider using Xerces.
[14.09.2017 10:55:22:787 EET] 00000112 XmlUtils      I org.docx4j.XmlUtils <clinit> actual: org.apache.xerces.jaxp.DocumentBuilderFactoryImpl
[14.09.2017 10:55:22:801 EET] 00000112 ContentTypeMa I org.docx4j.openpackaging.contenttype.ContentTypeManager createPackage Detected WordProcessingML package 
[14.09.2017 10:55:22:805 EET] 00000112 Load3         I org.docx4j.openpackaging.io3.Load3 get Instantiated package of type org.docx4j.openpackaging.packages.WordprocessingMLPackage
[14.09.2017 10:55:22:813 EET] 00000112 XPathFactoryU I org.docx4j.utils.XPathFactoryUtil getXPathFactory xpath implementation: org.apache.xpath.jaxp.XPathFactoryImpl
[14.09.2017 10:55:22:817 EET] 00000112 ContentTypeMa I org.docx4j.openpackaging.contenttype.ContentTypeManager CreateDocPropsCustomPartObject Using DocPropsCustomPart ...
[14.09.2017 10:55:22:834 EET] 00000112 SystemOut     O 2017-09-14 10:55:22,833 [WebContainer : 2] ERROR tr.com.cs.aurora.auroracore.utility.CSAbstractCaller  - java.lang.NullPointerException at line 347
null
CONS_ADMIN_TRANSLATE_HTML_TO_WORD
tr.com.cs.banking.loans.consumerloans.instalmentloans.bean.InstalmentContractManager
translateHTMLToWord
java.lang.NullPointerException
	at org.docx4j.openpackaging.io.Load.registerCustomXmlDataStorageParts(Load.java:347)
	at org.docx4j.openpackaging.io3.Load3.get(Load3.java:174)
	at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:462)
	at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:379)
	at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:345)
	at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:310)
	at org.docx4j.openpackaging.packages.WordprocessingMLPackage.load(WordprocessingMLPackage.java:180)
	at tr.com.cs.banking.loans.consumerloans.instalmentloans.bean.InstalmentContractManager.translateHTMLToWord(InstalmentContractManager.java:2017)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at tr.com.cs.aurora.auroracore.utility.CSAbstractCaller.call(lqb:122)
	at tr.com.cs.aurora.extensions.server.banking.CSBankingCaller.call(CSBankingCaller.java:34)
	at tr.com.cs.aurora.auroracore.utility.CSCaller.call(mtb:87)
	at tr.com.cs.aurora.auroracore.listener.ejb.ListenerBean.executeService(nxb:79)
	at tr.com.cs.aurora.auroracore.listener.ejb.ListenerBean.execute(nxb:15)
	at tr.com.cs.aurora.auroracore.listener.ejb.EJSLocalStatelessListenerBean_179455c0.execute(Unknown Source)
	at tr.com.cs.aurora.auroracore.listener.ejb.ListenerClient.execute(uvb:75)
	at tr.com.cs.aurora.auroracore.listener.servlet.command.server.CommandRemoteCall.execute$Impl(sfb:96)
	at tr.com.cs.aurora.auroracore.listener.servlet.command.server.CommandRemoteCall.execute(sfb:101)
	at tr.com.cs.aurora.utility.command.SCommand.executeCommand(pe:59)
	at tr.com.cs.aurora.auroracore.listener.servlet.ListenerServlet.execute(bqb:97)
	at tr.com.cs.aurora.auroracore.listener.servlet.ListenerServlet.doPost(bqb:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1233)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:782)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:481)
	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1114)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:87)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:949)
	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:200)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:463)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:530)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:316)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:287)
	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
	at com.ibm.io.async.AsyncChannelFuture$1.run(AsyncChannelFuture.java:205)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)
[14.09.2017 10:55:22:835 EET] 00000112 SystemOut     O [ERROR] java.lang.NullPointerException at line 347

**Comment by plutext** [comment]
Looks like it is happening at
https://github.com/plutext/docx4j/blob/master/src/main/java/org/docx4j/openpackaging/io/Load.java#L347
so ItemId is null.

May be similar to
https://www.docx4java.org/forums/websphere-and-domino-f26/npe-in-customxmlbinding-with-old-jaxb-t1170.html

**Comment by nevzatbayar** [comment]
Thanks for answer.  I know exception happen at which place. In same code, I dont get error in local but error occurs on server.  What should I do to solve problem?

**Comment by plutext** [comment]
Start by providing more information (which Java, which JAXB etc).

You might have more luck posting somewhere where there are WebSphere
experts.

**Comment by nevzatbayar** [comment]
Hi,
I'm using these versions.
java 1.6.0
Websphere 8.5.5.11
jaxb-api-2.1.jar
jaxb-impl-2.1.6.jar
jaxb-xjc-2.1.6.jar
jaxb-ATM.jar
jaxb-rt-1.0-ea.jar
