### ISSUE TITLE
docx4j java.lang.NoClassDefFoundError (WebSphere)

### ISSUE THREAD

**Issue by nevzatbayar** [plutext/docx4j#264]
Hi All,

I want to convert html to docx. I get following error. Can anybody help me 

my java and jars versions.
java 1.6
<dependency org="org.docx4j" name="docx4j" rev="3.3.5" conf="default"/>
<dependency org="org.docx4j" name="docx4j-ImportXHTML" rev="3.3.4" conf="default"/>
<dependency org="org.slf4j" name="slf4j-api" rev="1.7.25" conf="default"/>
<dependency org="org.docx4j" name="xhtmlrenderer" rev="3.0.0"/>
<dependency org="com.google.guava" name="guava" rev="19.0"/>
<dependency org="com.lowagie" name="itext" rev="2.1.7"/>
<dependency org="xalan" name="xalan" rev="2.7.1" conf="default"/>
<dependency org="xalan" name="serializer" rev="2.7.1"/> 
<dependency org="org.eclipse.persistence" name="org.eclipse.persistence.moxy" rev="2.5.1"/>
<dependency org="org.docx4j" name="docx4j-MOXy-JAXBContext" rev="3.0.0"/>

java.lang.NoClassDefFoundError at line 91
org.docx4j.jaxb.Context (initialization failure)

&#x09;at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:91)
&#x09;at org.docx4j.openpackaging.contenttype.ContentTypeManager.parseContentTypesFile(ContentTypeManager.java:733)
&#x09;at org.docx4j.openpackaging.io3.Load3.get(Load3.java:134)
&#x09;at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:462)
&#x09;at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:379)
&#x09;at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:345)
&#x09;at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:310)
&#x09;at org.docx4j.openpackaging.packages.WordprocessingMLPackage.load(WordprocessingMLPackage.java:180)
&#x09;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
&#x09;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
&#x09;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
&#x09;at java.lang.reflect.Method.invoke(Method.java:508)
&#x09;at tr.com.cs.aurora.auroracore.utility.CSAbstractCaller.call(lqb:122)
&#x09;at tr.com.cs.aurora.extensions.server.banking.CSBankingCaller.call(CSBankingCaller.java:34)
&#x09;at tr.com.cs.aurora.auroracore.utility.CSCaller.call(mtb:87)
&#x09;at tr.com.cs.aurora.auroracore.listener.ejb.ListenerBean.executeService(nxb:79)
&#x09;at tr.com.cs.aurora.auroracore.listener.ejb.ListenerBean.execute(nxb:15)
&#x09;at tr.com.cs.aurora.auroracore.listener.ejb.EJSLocalStatelessListenerBean_179455c0.execute(Unknown Source)
&#x09;at tr.com.cs.aurora.auroracore.listener.ejb.ListenerClient.execute(uvb:75)
&#x09;at tr.com.cs.aurora.auroracore.listener.servlet.command.server.CommandRemoteCall.execute$Impl(sfb:96)
&#x09;at tr.com.cs.aurora.auroracore.listener.servlet.command.server.CommandRemoteCall.execute(sfb:101)
&#x09;at tr.com.cs.aurora.utility.command.SCommand.executeCommand(pe:59)
&#x09;at tr.com.cs.aurora.auroracore.listener.servlet.ListenerServlet.execute(bqb:97)
&#x09;at tr.com.cs.aurora.auroracore.listener.servlet.ListenerServlet.doPost(bqb:68)
&#x09;at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)
&#x09;at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
&#x09;at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1233)
&#x09;at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:782)
&#x09;at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:481)
&#x09;at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178)
&#x09;at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1114)
&#x09;at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:87)
&#x09;at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:949)
&#x09;at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
&#x09;at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:200)
&#x09;at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:463)
&#x09;at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:530)
&#x09;at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:316)
&#x09;at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88)
&#x09;at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
&#x09;at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
&#x09;at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
&#x09;at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
&#x09;at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
&#x09;at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
&#x09;at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
&#x09;at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)
Caused by: java.lang.NoClassDefFoundError: org.eclipse.persistence.exceptions.JAXBException
&#x09;at java.lang.J9VMInternals.prepareClassImpl(Native Method)
&#x09;at java.lang.J9VMInternals.prepare(J9VMInternals.java:291)
&#x09;at java.lang.Class.getMethod(Class.java:1216)
&#x09;at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:131)
&#x09;at javax.xml.bind.ContextFinder.find(ContextFinder.java:258)
&#x09;at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:372)
&#x09;at org.docx4j.jaxb.Context.&lt;clinit&gt;(Context.java:146)
&#x09;... 47 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.persistence.exceptions.JAXBException
&#x09;at java.net.URLClassLoader.findClass(URLClassLoader.java:607)
&#x09;at com.ibm.ws.bootstrap.ExtClassLoader.findClass(ExtClassLoader.java:243)
&#x09;at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:846)
&#x09;at java.lang.ClassLoader.loadClass(ClassLoader.java:825)
&#x09;at com.ibm.ws.bootstrap.ExtClassLoader.loadClass(ExtClassLoader.java:134)
&#x09;at java.lang.ClassLoader.loadClass(ClassLoader.java:805)
&#x09;at com.ibm.ws.classloader.ProtectionClassLoader.loadClass(ProtectionClassLoader.java:62)
&#x09;at com.ibm.ws.classloader.ProtectionClassLoader.loadClass(ProtectionClassLoader.java:58)
&#x09;at com.ibm.ws.classloader.CompoundClassLoader.loadClass(CompoundClassLoader.java:586)
&#x09;at java.lang.ClassLoader.loadClass(ClassLoader.java:805)

**Comment by jaboj78** [comment]
HI,

You could try to add org.eclipse.persistence.core-2.6.4.jar and/or other jars from org.eclipse.persistence.moxy dependency?

/ Jacob
