### ISSUE TITLE
InputStream mark/reset error

### ISSUE THREAD

**Issue by devishell** [plutext/docx4j#272]
org.docx4j.openpackaging.exceptions.Docx4JException: Error reading from the stream
Caused by: java.io.IOException: Mark has been invalidated.
                                                                     at java.io.BufferedInputStream.reset(BufferedInputStream.java:336)
                                                                     at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:371)
/////
in android,getContext().getAssets().open(filename) return a child class extends inputstream,and it overides
its markSupported/read/mark/reset method,etc; the reset method is native,some of them as well

@plutext

**Comment by devishell** [comment]
how to resolve it?
