### ISSUE TITLE
deleteEmbeddedFontTempFiles cause NullPointerException

### ISSUE THREAD

**Issue by devishell** [plutext/docx4j#274]
Exception exporting package
                                                                 org.docx4j.openpackaging.exceptions.Docx4JException: Exception exporting package
                                                                     at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:109)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File[] java.io.File.listFiles()' on a null object reference
                                                                     at org.docx4j.openpackaging.parts.WordprocessingML.ObfuscatedFontPart.deleteEmbeddedFontTempFiles(ObfuscatedFontPart.java:263)
                                                                     at org.docx4j.openpackaging.parts.WordprocessingML.FontTablePart.deleteEmbeddedFontTempFiles(FontTablePart.java:161)
                                                                     at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:91)
                                                                     at handprobe.components.PatientInfo.ui.ReportFragment$1.doBackground(ReportFragment.java:221) 
                                                                     at org.xutils.common.task.TaskProxy$1.run(TaskProxy.java:62) 
                                                                     at org.xutils.common.task.PriorityRunnable.run(PriorityRunnable.java:21) 
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by devishell** [comment]
just set in android
Docx4jProperties.setProperty("docx4j.openpackaging.parts.WordprocessingML.ObfuscatedFontPart.tmpFontDir",getActivity().getExternalCacheDir()+"/tempFont");
