### ISSUE TITLE
unmarshaller gives NumberFormatException for <w:tblW w:type="pct" w:w="5000.0"/>

### ISSUE THREAD

**Issue by fdellwing** [plutext/docx4j#298]
So I'm here again with a problem. This time we are unable to get the content of docx files created with pandoc (2.2.1).

```java
WordprocessingMLPackage wmlp = Docx4J.load(new File(file));
MainDocumentPart docPart = wmlp.getMainDocumentPart();

List<Object> content = docPart.getContent();
```
This is broken as well:
```java
List<Object> trs = docPart.getJAXBNodesViaXPath("//w:tr", false);
```

The errorlog is pretty big, so I attached it as txt file. It seems like it tries to parse the w:w as integer and fails to do so because it is a double.

Also attached is a docx file to reproduce.

[Kontrollbericht-1527679144919.docx](https://github.com/plutext/docx4j/files/2053658/Kontrollbericht-1527679144919.docx)
[docx4j_NFE.txt](https://github.com/plutext/docx4j/files/2053650/docx4j_NFE.txt)

**Comment by fdellwing** [comment]
Ok I tried it with

```xsl
<xsl:when test="../@w:type='dxa' or local-name(..)='pgSz' or local-name(..)='gridCol' or ../@w:type='pct'">
    <xsl:attribute name="w:w"><xsl:value-of select="format-number(., '#')" /></xsl:attribute>
</xsl:when>
```

But it does not work somehow, it now takes the whole `5000.0` instead of `.0`.

```
Schwerwiegend:   java.lang.NumberFormatException: For input string: "5000.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.math.BigInteger.<init>(BigInteger.java:470)
	at java.math.BigInteger.<init>(BigInteger.java:606)
	at com.sun.xml.bind.DatatypeConverterImpl._parseInteger(DatatypeConverterImpl.java:90)
	at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$21.parse(RuntimeBuiltinLeafInfoImpl.java:792)
	at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$21.parse(RuntimeBuiltinLeafInfoImpl.java:790)
	at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.parse(TransducedAccessor.java:245)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:210)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:576)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:555)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.handleStartElement(StAXStreamConnector.java:246)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:180)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:415)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:386)
	at org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware.unmarshal(JaxbXmlPartXPathAware.java:445)
	at org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware.unmarshal(JaxbXmlPartXPathAware.java:346)
	at org.docx4j.openpackaging.parts.JaxbXmlPart.getContents(JaxbXmlPart.java:176)
	at org.docx4j.openpackaging.parts.JaxbXmlPart.getJaxbElement(JaxbXmlPart.java:198)
```

I tried it in https://www.freeformatter.com/xsl-transformer.html and it works there. Any more ideas?

**Comment by fdellwing** [comment]
Ok even setting
```xsl
<xsl:when test="../@w:type='dxa' or local-name(..)='pgSz' or local-name(..)='gridCol' or ../@w:type='pct'">
    <xsl:attribute name="w:w">5000</xsl:attribute>
</xsl:when>
```
does not change it.

So I think it is another problem? It gets thrown in the TOC generator..

```
Schwerwiegend:   2838276 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - toc 1 style not defined in styles part; falling back to configured default
Schwerwiegend:   2838278 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - Added a styles definition for toc 1
Schwerwiegend:   2838278 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - toc 2 style not defined in styles part; falling back to configured default
Schwerwiegend:   2838278 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - Added a styles definition for toc 2
Schwerwiegend:   2838278 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - toc 3 style not defined in styles part; falling back to configured default
Schwerwiegend:   2838279 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - Added a styles definition for toc 3
Schwerwiegend:   2838279 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - toc 4 style not defined in styles part; falling back to configured default
Schwerwiegend:   2838279 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - Added a styles definition for toc 4
Schwerwiegend:   2838280 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - toc 5 style not defined in styles part; falling back to configured default
Schwerwiegend:   2838280 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - Added a styles definition for toc 5
Schwerwiegend:   2838280 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - toc 6 style not defined in styles part; falling back to configured default
Schwerwiegend:   2838280 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - Added a styles definition for toc 6
Schwerwiegend:   2838281 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - toc 7 style not defined in styles part; falling back to configured default
Schwerwiegend:   2838281 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - Added a styles definition for toc 7
Schwerwiegend:   2838281 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - toc 8 style not defined in styles part; falling back to configured default
Schwerwiegend:   2838282 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - Added a styles definition for toc 8
Schwerwiegend:   2838282 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - toc 9 style not defined in styles part; falling back to configured default
Schwerwiegend:   2838283 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - Added a styles definition for toc 9
Schwerwiegend:   2838283 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - Hyperlink style not defined in styles part; falling back to configured default
Schwerwiegend:   2838284 [http-listener-1(3)] INFO org.docx4j.toc.TocStyles - Added a styles definition for Hyperlink
Schwerwiegend:   2838290 [http-listener-1(3)] WARN org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware - For input string: "5000.0"
Schwerwiegend:   java.lang.NumberFormatException: For input string: "5000.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.math.BigInteger.<init>(BigInteger.java:470)
	at java.math.BigInteger.<init>(BigInteger.java:606)
	at com.sun.xml.bind.DatatypeConverterImpl._parseInteger(DatatypeConverterImpl.java:90)
	at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$21.parse(RuntimeBuiltinLeafInfoImpl.java:792)
	at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$21.parse(RuntimeBuiltinLeafInfoImpl.java:790)
	at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.parse(TransducedAccessor.java:245)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:210)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:576)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:555)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.handleStartElement(StAXStreamConnector.java:246)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:180)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:415)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:386)
	at org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware.unmarshal(JaxbXmlPartXPathAware.java:445)
	at org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware.unmarshal(JaxbXmlPartXPathAware.java:346)
	at org.docx4j.openpackaging.parts.JaxbXmlPart.getContents(JaxbXmlPart.java:176)
	at org.docx4j.openpackaging.parts.JaxbXmlPart.getJaxbElement(JaxbXmlPart.java:198)
	at org.docx4j.toc.TocGenerator.generateToc(TocGenerator.java:212)
	at org.docx4j.toc.TocGenerator.generateToc(TocGenerator.java:191)
	at util.DOCXUtil.createToc(DOCXUtil.java:165)
```

**Comment by plutext** [comment]
See now https://github.com/plutext/docx4j/commit/ba68d3ab95e03ea714fa5ea76dadeffeaaf3bca0
