### ISSUE TITLE
Error  The content of elements must consist of well-formed character data or markup.

### ISSUE THREAD

**Issue by fffeniksss** [plutext/docx4j#311]
package ru.simplexsoftware.constructorOfDocuments;

import org.docx4j.convert.in.xhtml.XHTMLImporterImpl;
import org.docx4j.openpackaging.exceptions.Docx4JException;
import org.docx4j.openpackaging.exceptions.InvalidFormatException;
import org.docx4j.openpackaging.packages.WordprocessingMLPackage;
import org.docx4j.openpackaging.parts.WordprocessingML.NumberingDefinitionsPart;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.w3c.dom.Document;
import org.w3c.tidy.Tidy;
import org.xml.sax.InputSource;
import ru.simplexsoftware.constructorOfDocuments.Utils.DocxUtil;

import javax.xml.bind.JAXBException;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.sax.SAXSource;
import javax.xml.transform.sax.SAXTransformerFactory;
import javax.xml.transform.stream.StreamResult;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.StringWriter;
import java.io.UnsupportedEncodingException;
import java.io.Writer;
import java.util.Scanner;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration( locations={"classpath:applicationContext.xml"} )
public class MainTest {
    private static final Logger LOG = LoggerFactory.getLogger(MainTest.class);

    @Test
    public void runTest() throws IOException {
        File file = new File("test.docx");
        file.createNewFile();
        String html=new String();
        FileInputStream fstream = new FileInputStream("C:\\Users\\User\\IdeaProjects\\constructor\\src\\test\\java\\ru\\simplexsoftware\\constructorOfDocuments\\doc.html");
        BufferedReader br = new BufferedReader(new InputStreamReader(fstream));
        String strLine;
        while ((strLine = br.readLine()) != null){
            html=html+" "+strLine;
        }
        InputStream in = new ByteArrayInputStream(createDocx(html));
        org.apache.wicket.util.file.Files.writeTo(file, in);

    }
    public static byte[] createDocx(String htmlDoc){
        WordprocessingMLPackage wordMLPackage = null;
        try {
            wordMLPackage = WordprocessingMLPackage.createPackage();
        } catch (InvalidFormatException e) {
            LOG.error(e.getMessage(),e);
        }

        NumberingDefinitionsPart ndp = null;
        try {
            ndp = new NumberingDefinitionsPart();
        } catch (InvalidFormatException e) {
            LOG.error(e.getMessage(),e);
        }
        try {
            wordMLPackage.getMainDocumentPart().addTargetPart(ndp);
        } catch (InvalidFormatException e) {
            LOG.error(e.getMessage(),e);
        }
        try {
            ndp.unmarshalDefaultNumbering();
        } catch (JAXBException e) {
            LOG.error(e.getMessage(),e);
        }

        XHTMLImporterImpl xHTMLImporter = new XHTMLImporterImpl(wordMLPackage);
        xHTMLImporter.setHyperlinkStyle("Hyperlink");
        Tidy tidy = new Tidy();
        tidy.setInputEncoding("UTF-8");
        tidy.setOutputEncoding("UTF-8");
        tidy.setRawOut(true);

        tidy.setXHTML(true);

        ByteArrayInputStream inputStream = null;
        try {
            inputStream = new ByteArrayInputStream(htmlDoc.getBytes("UTF-8"));
        } catch (UnsupportedEncodingException e) {
            LOG.error(e.getMessage(),e);
        }
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        tidy.parseDOM(inputStream, outputStream);

        // Convert the XHTML, and add it into the empty docx we made
        try {
            wordMLPackage.getMainDocumentPart().getContent().addAll(
                    xHTMLImporter.convert(new ByteArrayInputStream(outputStream.toByteArray()), null));
        } catch (Docx4JException e) {
            LOG.error(e.getMessage(),e);
        }

        ByteArrayOutputStream output = new ByteArrayOutputStream();

        try {
            wordMLPackage.save(output);
        } catch (Docx4JException e) {
            LOG.error(e.getMessage(),e);
        }

        return output.toByteArray();
    }
    }
/************************************************************************************************/
org.docx4j.org.xhtmlrenderer.exception WARNING:: Unhandled exception. Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 87; The content of elements must consist of well-formed character data or markup.

org.docx4j.org.xhtmlrenderer.util.XRRuntimeException: Can't load the XML resource (using TRaX transformer). org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 87; The content of elements must consist of well-formed character data or markup.

	at org.docx4j.org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:192)
	at org.docx4j.org.xhtmlrenderer.resource.XMLResource.load(XMLResource.java:71)
	at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.convert(XHTMLImporterImpl.java:537)
	at ru.simplexsoftware.constructorOfDocuments.Utils.DocxUtil.createDocx(DocxUtil.java:68)
	at ru.simplexsoftware.constructorOfDocuments.MainTest.runTest(MainTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 87; The content of elements must consist of well-formed character data or markup.
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
	at org.docx4j.org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:190)
	... 32 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 16; columnNumber: 87; The content of elements must consist of well-formed character data or markup.
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	... 33 more
[html.txt](https://github.com/plutext/docx4j/files/2231380/html.txt)

**Comment by fffeniksss** [comment]
In the end I attached the document html

**Comment by plutext** [comment]
As it says, org.xml.sax.SAXParseException; **lineNumber: 16; columnNumber: 87; The content of elements must consist of well-formed character data or markup.**

Check your input is valid XML.
