### ISSUE TITLE
docx4j  add xalan.jar , then  appear  SAXException and DOMException， use spring.xml

### ISSUE THREAD

**Issue by muxiaobai** [plutext/docx4j#339]
###  jdk8.0  tomcat8.5 spring 4.3.12,  and use itext,

org.apache.commons.configuration2.ex.ConfigurationException: Unable to load the configuration
	at org.apache.commons.configuration2.XMLConfiguration.load(XMLConfiguration.java:1040)
	at org.apache.commons.configuration2.XMLConfiguration.read(XMLConfiguration.java:1001)
	at org.apache.commons.configuration2.io.FileHandler.loadFromStreamDirectly(FileHandler.java:1080)
	at org.apache.commons.configuration2.io.FileHandler.loadFromStream(FileHandler.java:1055)
	at org.apache.commons.configuration2.io.FileHandler.load(FileHandler.java:990)
	at org.apache.commons.configuration2.io.FileHandler.load(FileHandler.java:973)
	at org.apache.commons.configuration2.io.FileHandler.load(FileHandler.java:702)
	at org.apache.commons.configuration2.builder.FileBasedConfigurationBuilder.initFileHandler(FileBasedConfigurationBuilder.java:312)
	at org.apache.commons.configuration2.builder.FileBasedConfigurationBuilder.initResultInstance(FileBasedConfigurationBuilder.java:291)
	at org.apache.commons.configuration2.builder.FileBasedConfigurationBuilder.initResultInstance(FileBasedConfigurationBuilder.java:60)
	at org.apache.commons.configuration2.builder.BasicConfigurationBuilder.createResult(BasicConfigurationBuilder.java:421)
	at org.apache.commons.configuration2.builder.BasicConfigurationBuilder.getConfiguration(BasicConfigurationBuilder.java:285)
	at org.apache.commons.configuration2.builder.fluent.Configurations.xml(Configurations.java:403)
	at cn.forp.framework.platform.SystemInit.init(SystemInit.java:92)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4978)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5290)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1140)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.configuration2.ex.ConfigurationException: javax.xml.transform.TransformerException: org.xml.sax.SAXException: NAMESPACE_ERR: 尝试以错误的名称空间创建或更改方式来创建或更改对象。
org.w3c.dom.DOMException: NAMESPACE_ERR: 尝试以错误的名称空间创建或更改方式来创建或更改对象。
	at org.apache.commons.configuration2.XMLDocumentHelper.transform(XMLDocumentHelper.java:235)
	at org.apache.commons.configuration2.XMLDocumentHelper.copyDocument(XMLDocumentHelper.java:319)
	at org.apache.commons.configuration2.XMLDocumentHelper.forSourceDocument(XMLDocumentHelper.java:156)
	at org.apache.commons.configuration2.XMLConfiguration.load(XMLConfiguration.java:1030)
	... 30 more
Caused by: javax.xml.transform.TransformerException: org.xml.sax.SAXException: NAMESPACE_ERR: 尝试以错误的名称空间创建或更改方式来创建或更改对象。
org.w3c.dom.DOMException: NAMESPACE_ERR: 尝试以错误的名称空间创建或更改方式来创建或更改对象。
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:401)
	at org.apache.commons.configuration2.XMLDocumentHelper.transform(XMLDocumentHelper.java:231)
	... 33 more
Caused by: org.xml.sax.SAXException: NAMESPACE_ERR: 尝试以错误的名称空间创建或更改方式来创建或更改对象。
org.w3c.dom.DOMException: NAMESPACE_ERR: 尝试以错误的名称空间创建或更改方式来创建或更改对象。
	at org.apache.xml.utils.DOMBuilder.startElement(DOMBuilder.java:401)
	at org.apache.xalan.transformer.TransformerIdentityImpl.startElement(TransformerIdentityImpl.java:1073)
	at org.apache.xml.serializer.TreeWalker.startNode(TreeWalker.java:359)
	at org.apache.xml.serializer.TreeWalker.traverse(TreeWalker.java:145)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:390)
	... 34 more
Caused by: org.w3c.dom.DOMException: NAMESPACE_ERR: 尝试以错误的名称空间创建或更改方式来创建或更改对象。
	at com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.checkDOMNSErr(CoreDocumentImpl.java:2547)
	at com.sun.org.apache.xerces.internal.dom.AttrNSImpl.setName(AttrNSImpl.java:117)
	at com.sun.org.apache.xerces.internal.dom.AttrNSImpl.<init>(AttrNSImpl.java:78)
	at com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.createAttributeNS(CoreDocumentImpl.java:2164)
	at com.sun.org.apache.xerces.internal.dom.ElementImpl.setAttributeNS(ElementImpl.java:659)
	at org.apache.xml.utils.DOMBuilder.startElement(DOMBuilder.java:365)
	... 38 more

**Comment by plutext** [comment]
Can't make much sense of this, other than org.w3c.dom.DOMException: NAMESPACE_ERR

Closing, but feel free to re-open with more details
