### ISSUE TITLE
NPE in org.docx4j.jaxb.NamespacePrefixMapperUtils (6.1.1)

### ISSUE THREAD

**Issue by epihel** [plutext/docx4j#345]
Calling `org.docx4j.jaxb.NamespacePrefixMapperUtils#getPrefixMapper` in a unit test throws an NPE every time in line 61:

```
if (Context.getJaxbImplementation() == JAXBImplementation.ECLIPSELINK_MOXy) {
```

because `org.docx4j.jaxb.Context` is null.

```
java.lang.ExceptionInInitializerError
	at org.docx4j.jaxb.NamespacePrefixMapperUtils.getPrefixMapper(NamespacePrefixMapperUtils.java:61)
Caused by: java.lang.NullPointerException
	at org.docx4j.jaxb.Context.<clinit>(Context.java:127)
	... 38 more
```

This bug also exists in `6.1.0`, but does not exist in `6.0.1`.

**Comment by plutext** [comment]
You can't do much in docx4j without a Context object. 

Can you create it before calling NamespacePrefixMapperUtils.getPrefixMapper()?

**Comment by epihel** [comment]
For now, I've copied and pasted the code from `org.docx4j.jaxb.Context` line 156 into my unit tests and that works. Is there a way to make this easily available without copying and pasting?

```
tempContext = JAXBContext.newInstance("org.docx4j.wml:org.docx4j.w14:org.docx4j.w15:" +
					"org.docx4j.com.microsoft.schemas.office.word.x2006.wordml:" +
					"org.docx4j.dml:org.docx4j.dml.chart:org.docx4j.dml.chart.x2007:org.docx4j.dml.chartDrawing:org.docx4j.dml.compatibility:org.docx4j.dml.diagram:org.docx4j.dml.lockedCanvas:org.docx4j.dml.picture:org.docx4j.dml.wordprocessingDrawing:org.docx4j.dml.spreadsheetdrawing:org.docx4j.dml.diagram2008:" +
					// All VML stuff is here, since compiling it requires WML and DML (and MathML), but not PML or SML
					"org.docx4j.vml:org.docx4j.vml.officedrawing:org.docx4j.vml.wordprocessingDrawing:org.docx4j.vml.presentationDrawing:org.docx4j.vml.spreadsheetDrawing:org.docx4j.vml.root:" +
					"org.docx4j.docProps.coverPageProps:" +
					"org.opendope.xpaths:org.opendope.conditions:org.opendope.questions:org.opendope.answers:org.opendope.components:org.opendope.SmartArt.dataHierarchy:" +
					"org.docx4j.math:" +
					"org.docx4j.sharedtypes:org.docx4j.bibliography:" +
					"org.docx4j.com.microsoft.schemas.office.word.x2010.wordprocessingDrawing:" +
					"org.docx4j.com.microsoft.schemas.office.word.x2010.wordprocessingShape:" +
					"org.docx4j.w15symex:org.docx4j.w16cid:" +
					"org.docx4j.com.microsoft.schemas.office.webextensions.taskpanes_2010_11:" +
					"org.docx4j.com.microsoft.schemas.office.webextensions.webextension_2010_11", classLoader,
					ProviderProperties.getProviderProperties() );
```

**Comment by plutext** [comment]
You shouldn't need to do that; its enough to do anything which causes Context to be initialised.  

For example `JAXBContext jc = Context.jc` or `org.docx4j.wml.ObjectFactory factory = Context.getWmlObjectFactory()`

**Comment by epihel** [comment]
Confirmed that `JAXBContext jc = Context.jc` worked. Thanks! Not sure what was happening earlier.
