### ISSUE TITLE
Cannot load docx files with missing relationships.

### ISSUE THREAD

**Issue by awerdx520** [plutext/docx4j#414]
Exception:
`org.docx4j.openpackaging.exceptions.Docx4JException: For source /word/document.xml, cannot find part NULL from rel rId4=../NULL
	at org.docx4j.openpackaging.io3.Load3.getRawPart(Load3.java:626)
	at org.docx4j.openpackaging.io3.Load3.getPart(Load3.java:372)
	at org.docx4j.openpackaging.io3.Load3.addPartsFromRelationships(Load3.java:278)
	at org.docx4j.openpackaging.io3.Load3.getPart(Load3.java:400)
	at org.docx4j.openpackaging.io3.Load3.addPartsFromRelationships(Load3.java:278)
	at org.docx4j.openpackaging.io3.Load3.get(Load3.java:196)
	at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:561)
	at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:410)
	at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:376)
	at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:341)
	at org.docx4j.openpackaging.packages.WordprocessingMLPackage.load(WordprocessingMLPackage.java:180)
	at org.docx4j.Docx4J.load(Docx4J.java:246)`

Relationships:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/custom-properties" Target="docProps/custom.xml"/>
</Relationships>`

word/document.xml -> rId4
`<w:drawing>
<wp:inline distT="0" distB="0" distL="114300" distR="114300">
<wp:extent cx="304800" cy="304800"/>
<wp:effectExtent l="0" t="0" r="0" b="0"/>
<wp:docPr id="1" name="图片 1" descr="IMG_256"/>
<wp:cNvGraphicFramePr>
<a:graphicFrameLocks xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" noChangeAspect="1"/>
</wp:cNvGraphicFramePr>
<a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">
<a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
<pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">
<pic:nvPicPr>
<pic:cNvPr id="1" name="图片 1" descr="IMG_256"/>
<pic:cNvPicPr>
<a:picLocks noChangeAspect="1"/>
</pic:cNvPicPr>
</pic:nvPicPr>
<pic:blipFill>
<a:blip r:embed="rId4"/>
<a:stretch>
<a:fillRect/>
</a:stretch>
</pic:blipFill>
<pic:spPr>
<a:xfrm>
<a:off x="0" y="0"/>
<a:ext cx="304800" cy="304800"/>
</a:xfrm>
<a:prstGeom prst="rect">
<a:avLst/>
</a:prstGeom>
<a:noFill/>
<a:ln w="9525">
<a:noFill/>
</a:ln>
</pic:spPr>
</pic:pic>
</a:graphicData>
</a:graphic>
</wp:inline>
</w:drawing>
`
[sample.zip](https://github.com/plutext/docx4j/files/5116614/sample.zip)

**Comment by plutext** [comment]
You need to look at word\_rels\document.xml.rels

In your example this contains:
```
><Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../NULL"/>
```

**Comment by awerdx520** [comment]
Sorry, I did not describe my problem completely. I know the reason for the error, but I cannot control the source of the file. This error is an exception thrown when I execute Docx4j.load(file).
How can I generate WordprocessPackage objects like this? Can I not use docx4j for this kind of file? Do I have to fix the rId reference to continue using docx4j to operate it?

**Comment by jasonisgraham** [comment]
> Sorry, I did not describe my problem completely. I know the reason for the error, but I cannot control the source of the file. This error is an exception thrown when I execute Docx4j.load(file).
> How can I generate WordprocessPackage objects like this? Can I not use docx4j for this kind of file? Do I have to fix the rId reference to continue using docx4j to operate it?

My use-case is the same.  So, FWIW, I've been working around this issue by determining broken relationships and removing them from `document.xml.rels`.

**Comment by vinayrambhiaSNC** [comment]
@jasonisgraham how are you finding those broken relationships and removing it? copying the logic of load3.java to load relationship and getrawpart?   

I am having same problem where target having case mismatch. customXml/ vs customXML/
