### ISSUE TITLE
ERROR org.docx4j.utils.XmlSerializerUtil - null on Docx4J.toFO(foSettings, OutputStream, Docx4J.FLAG_EXPORT_PREFER_XSL)

### ISSUE THREAD

**Issue by mhanchini** [plutext/docx4j#423]
Hi.. I tried example https://github.com/plutext/docx4j/blob/master/docx4j-samples-docx-export-fo/src/main/java/org/docx4j/samples/ConvertOutPDFviaXSLFO.java

I am using Java 8 and org.docx4j 8.2.4 also the docx4j-export-fo 8.2.4

but I got this error : 

ERROR org.docx4j.utils.XmlSerializerUtil - null
java.lang.NullPointerException: null
	at org.apache.fop.layoutmgr.TraitSetter.setVisibility(TraitSetter.java:615)
	at org.apache.fop.layoutmgr.BlockLayoutManager.addAreas(BlockLayoutManager.java:334)
	at org.apache.fop.layoutmgr.AreaAdditionUtil.addAreas(AreaAdditionUtil.java:113)
	at org.apache.fop.layoutmgr.FlowLayoutManager.addAreas(FlowLayoutManager.java:367)
	at org.apache.fop.layoutmgr.inline.LineLayoutManager.addBlockArea(LineLayoutManager.java:1642)
	at org.apache.fop.layoutmgr.inline.LineLayoutManager.addAreas(LineLayoutManager.java:1479)
	at org.apache.fop.layoutmgr.BlockLayoutManager.addAreas(BlockLayoutManager.java:327)
	at org.apache.fop.layoutmgr.AreaAdditionUtil.addAreas(AreaAdditionUtil.java:113)
	at org.apache.fop.layoutmgr.FlowLayoutManager.addAreas(FlowLayoutManager.java:367)
	at org.apache.fop.layoutmgr.PageBreaker.addAreas(PageBreaker.java:315)
	at org.apache.fop.layoutmgr.PageBreaker.addAreasForFloats(PageBreaker.java:886)
	at org.apache.fop.layoutmgr.AbstractBreaker.addAreas(AbstractBreaker.java:713)
	at org.apache.fop.layoutmgr.AbstractBreaker.addAreas(AbstractBreaker.java:604)
	at org.apache.fop.layoutmgr.AbstractBreaker.addAreas(AbstractBreaker.java:599)
	at org.apache.fop.layoutmgr.PageBreaker.handleFloatLayout(PageBreaker.java:777)
	at org.apache.fop.layoutmgr.AbstractBreaker.doLayout(AbstractBreaker.java:427)
	at org.apache.fop.layoutmgr.PageBreaker.doLayout(PageBreaker.java:112)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:143)
	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:139)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at org.docx4j.org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1148)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1718)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at org.docx4j.org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:518)
	at org.docx4j.utils.XmlSerializerUtil.serialize(XmlSerializerUtil.java:51)
	at org.docx4j.utils.XmlSerializerUtil.serialize(XmlSerializerUtil.java:18)
	at org.docx4j.convert.out.fo.renderers.FORendererApacheFOP.render(FORendererApacheFOP.java:247)
	at org.docx4j.convert.out.fo.renderers.FORendererApacheFOP.render(FORendererApacheFOP.java:181)
	at org.docx4j.convert.out.fo.AbstractFOExporter.postprocess(AbstractFOExporter.java:168)
	at org.docx4j.convert.out.fo.AbstractFOExporter.postprocess(AbstractFOExporter.java:47)
	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:81)
	at org.docx4j.Docx4J.toFO(Docx4J.java:711)
	at com.komunitas.tester.docx.DefaultDocxToFo.main(DefaultDocxToFo.java:123)
org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:106)
org.docx4j.Docx4J.toFO(Docx4J.java:711)
com.komunitas.tester.docx.DefaultDocxToFo.main(DefaultDocxToFo.java:123)

**Comment by plutext** [comment]
what jars do you have on your classpath?

```
java.lang.NullPointerException: null
at org.apache.fop.layoutmgr.TraitSetter.setVisibility(TraitSetter.java:615)

```

What does TraitSetter.java say at line 615

**Comment by mhanchini** [comment]
My jars is :

		<dependency>
			<groupId>org.docx4j</groupId>
			<artifactId>docx4j-core</artifactId>
			<version>8.2.4</version>
		</dependency>
		
		<dependency>
			<groupId>org.docx4j</groupId>
			<artifactId>docx4j-JAXB-Internal</artifactId>
			<version>8.2.4</version>
		</dependency>
		
		<dependency>
			<groupId>org.docx4j</groupId>
			<artifactId>docx4j</artifactId>
			<version>6.1.2</version>
		</dependency>
		
		<dependency>
			<groupId>org.docx4j</groupId>
			<artifactId>docx4j-JAXB-ReferenceImpl</artifactId>
			<version>8.2.4</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>4.1.2</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>4.1.2</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml-schemas</artifactId>
			<version>4.1.2</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.xmlgraphics</groupId>
			<artifactId>fop</artifactId>
			<version>2.5</version>
		</dependency>
		
		<dependency>
			<groupId>org.docx4j</groupId>
			<artifactId>docx4j-export-fo</artifactId>
			<version>8.2.4</version>
		</dependency>
		
		<dependency>
			<groupId>org.docx4j</groupId>
			<artifactId>docx4j-documents4j-local</artifactId>
			<version>8.2.4</version>
		</dependency>

TraitSetter.java at line 615 : 

area.addTrait(Trait.VISIBILITY, v);

[sample-docx.docx](https://github.com/plutext/docx4j/files/5650252/sample-docx.docx)
[PERMOHONAN.docx](https://github.com/plutext/docx4j/files/5650253/PERMOHONAN.docx)
[NPH_BAST.docx](https://github.com/plutext/docx4j/files/5650254/NPH_BAST.docx)

this morning I tried rerun sample-docx success, PERMOHONAN.docx failure with the same exception, NPH_BAST.docx failure with the same exception.

when using https://github.com/plutext/docx4j/tree/master/docx4j-samples-documents4j-local/src/main/java/org/docx4j/samples/documents4j/local example result perfect as desire but I am affraid ubuntu server (production) doesn't have MS Office.

**Comment by plutext** [comment]
Remove  

```
	<dependency>
		<groupId>org.docx4j</groupId>
		<artifactId>docx4j</artifactId>
		<version>6.1.2</version>
	</dependency>
```
Both your docx work for me.  Try a new project with minimal deps; see https://github.com/plutext/docx4j/blob/master/docx4j-samples-docx-export-fo/pom.xml

**Comment by mhanchini** [comment]
I removed 

<dependency>
		<groupId>org.docx4j</groupId>
		<artifactId>docx4j</artifactId>
		<version>6.1.2</version>
</dependency>

Changed my docx files (remove drawing) and result success, but in the pdf file has red text :

NOT IMPLEMENTED: support for w:pict - without v:imagedata 

[NPH_BAST.pdf](https://github.com/plutext/docx4j/files/5652636/NPH_BAST.pdf)
