### ISSUE TITLE
Samples for pptx4j is not working because of an JAXB XSLT validation error

### ISSUE THREAD

**Issue by yavuztas** [plutext/docx4j#425]
Hello community, 

I was just trying the pptx4j samples under the module `docx4j-samples-pptx4j` but got an error like this:
```java
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"http://schemas.openxmlformats.org/presentationml/2006/main", local:"notesSz"). Expected elements are <{http://schemas.openxmlformats.org/markup-compatibility/2006}AlternateContent>,<{http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing}anchor>,<{http://schemas.openxmlformats.org/drawingml/2006/main}blip>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}bmkTgt>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}browseMode>,<{http://schemas.openxmlformats.org/drawingml/2006/chart}chart>,<{http://schemas.openxmlformats.org/drawingml/2006/chart}chartSpace>,<{http://schemas.microsoft.com/office/powerpoint/2012/main}chartTrackingRefBased>,<{http://schemas.microsoft.com/office/powerpoint/2013/main/command}chgInfo>,<{http://schemas.microsoft.com/office/powerpoint/2018/4/main}classification>,<{http://schemas.openxmlformats.org/presentationml/2006/main}cmAuthor>,<{http://schemas.openxmlformats.org/presentationml/2006/main}cmAuthorLst>,<{http://schemas.microsoft.com/office/powerpoint/2013/main/command}cmAuthorMkLst>,<{http://schemas.openxmlformats.org/presentationml/2006/main}cmLst>,<{http://schemas.microsoft.com/office/powerpoint/2013/main/command}cmMkLst>,<{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDef>,<{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDefHdr>,<{http://schemas.openxmlformats.org/drawingml/2006/diagram}colorsDefHdrLst>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}conveyor>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}creationId>,<{http://schemas.microsoft.com/office/drawing/2013/main/command}cxnSpMkLst>,<{http://schemas.openxmlformats.org/drawingml/2006/diagram}dataModel>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}defaultImageDpi>,<{http://schemas.microsoft.com/office/powerpoint/2015/main}designElem>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}discardImageEditData>,<{http://schemas.microsoft.com/office/powerpoint/2013/main/command}docMkLst>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}doors>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}extLst>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}ferris>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}flash>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}flip>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}flythrough>,<{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}from>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}gallery>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}glitter>,<{http://schemas.openxmlformats.org/drawingml/2006/main}graphic>,<{http://schemas.microsoft.com/office/drawing/2013/main/command}graphicFrameMkLst>,<{http://schemas.microsoft.com/office/drawing/2013/main/command}grpMkLst>,<{http://schemas.openxmlformats.org/presentationml/2006/main}handoutMaster>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}honeycomb>,<{http://schemas.microsoft.com/office/drawing/2013/main/command}inkMkLst>,<{http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing}inline>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}laserClr>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}laserTraceLst>,<{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDef>,<{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDefHdr>,<{http://schemas.openxmlformats.org/drawingml/2006/diagram}layoutDefHdrLst>,<{http://schemas.openxmlformats.org/drawingml/2006/compatibility}legacyDrawing>,<{http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas}lockedCanvas>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}media>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}modId>,<{http://schemas.microsoft.com/office/powerpoint/2015/09/main}morph>,<{http://schemas.openxmlformats.org/presentationml/2006/main}notes>,<{http://schemas.microsoft.com/office/powerpoint/2012/main}notesGuideLst>,<{http://schemas.openxmlformats.org/presentationml/2006/main}notesMaster>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}nvContentPartPr>,<{http://schemas.openxmlformats.org/presentationml/2006/main}oleObj>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}pan>,<{http://schemas.openxmlformats.org/drawingml/2006/picture}pic>,<{http://schemas.microsoft.com/office/drawing/2013/main/command}picMkLst>,<{http://schemas.microsoft.com/office/powerpoint/2012/main}presenceInfo>,<{http://schemas.openxmlformats.org/presentationml/2006/main}presentation>,<{http://schemas.openxmlformats.org/presentationml/2006/main}presentationPr>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}prism>,<{http://schemas.microsoft.com/office/powerpoint/2012/main}prstTrans>,<{http://schemas.microsoft.com/office/powerpoint/2017/10/main}readonlyRecommended>,<{http://schemas.openxmlformats.org/drawingml/2006/diagram}relIds>,<{http://schemas.microsoft.com/office/powerpoint/2015/10/main}revInfo>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}reveal>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}ripple>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}sectionLst>,<{http://schemas.microsoft.com/office/powerpoint/2016/sectionzoom}sectionZm>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}showEvtLst>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}showMediaCtrls>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}shred>,<{http://schemas.openxmlformats.org/presentationml/2006/main}sld>,<{http://schemas.microsoft.com/office/powerpoint/2013/main/command}sldBaseMkLst>,<{http://schemas.microsoft.com/office/powerpoint/2012/main}sldGuideLst>,<{http://schemas.openxmlformats.org/presentationml/2006/main}sldLayout>,<{http://schemas.microsoft.com/office/powerpoint/2013/main/command}sldLayoutMkLst>,<{http://schemas.openxmlformats.org/presentationml/2006/main}sldMaster>,<{http://schemas.microsoft.com/office/powerpoint/2013/main/command}sldMasterMkLst>,<{http://schemas.microsoft.com/office/powerpoint/2013/main/command}sldMkLst>,<{http://schemas.openxmlformats.org/presentationml/2006/main}sldSyncPr>,<{http://schemas.microsoft.com/office/powerpoint/2016/slidezoom}sldZm>,<{http://schemas.openxmlformats.org/presentationml/2006/main}sp>,<{http://schemas.microsoft.com/office/drawing/2013/main/command}spMkLst>,<{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDef>,<{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDefHdr>,<{http://schemas.openxmlformats.org/drawingml/2006/diagram}styleDefHdrLst>,<{http://schemas.microsoft.com/office/powerpoint/2016/summaryzoom}summaryZm>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}switch>,<{http://schemas.openxmlformats.org/drawingml/2006/diagram}t>,<{http://schemas.openxmlformats.org/presentationml/2006/main}tagLst>,<{http://schemas.openxmlformats.org/drawingml/2006/main}tbl>,<{http://schemas.openxmlformats.org/drawingml/2006/main}tblStyleLst>,<{http://schemas.openxmlformats.org/drawingml/2006/main}theme>,<{http://schemas.openxmlformats.org/drawingml/2006/main}themeManager>,<{http://schemas.openxmlformats.org/drawingml/2006/main}themeOverride>,<{http://schemas.microsoft.com/office/powerpoint/2012/main}threadingInfo>,<{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}to>,<{http://schemas.microsoft.com/office/powerpoint/2017/3/main}tracksInfo>,<{http://schemas.openxmlformats.org/drawingml/2006/chart}userShapes>,<{http://schemas.openxmlformats.org/presentationml/2006/main}viewPr>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}vortex>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}warp>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}wheelReverse>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}window>,<{http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing}wsDr>,<{http://schemas.microsoft.com/office/powerpoint/2010/main}xfrm>
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:712)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:232)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:227)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:94)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1117)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:542)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:524)
	at com.sun.xml.bind.v2.runtime.unmarshaller.InterningXmlVisitor.startElement(InterningXmlVisitor.java:45)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:137)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:214)
	at com.sun.xml.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:97)
	at com.sun.xml.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:80)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:341)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:322)
	at org.docx4j.XmlUtils.unmarshalString(XmlUtils.java:551)
	... 31 more
``` 
I guess the error originates while creating a package when the first JAXB unmarshalling happens in `org/docx4j/openpackaging/parts/PresentationML/MainPresentationPart.java`, line 397:
```java
// Create empty lists
Presentation.SldMasterIdLst masterIds = factory.createPresentationSldMasterIdLst();
Presentation.SldIdLst slideIds = factory.createPresentationSldIdLst();		
presentation.setSldMasterIdLst(masterIds);
presentation.setSldIdLst(slideIds);
		
presentation.setNotesSz( 
	(CTPositiveSize2D)XmlUtils.unmarshalString(DEFAULT_NOTES_SIZE, Context.jcPML, CTPositiveSize2D.class) );
```

You can reproduce the error just simply running the sample in `src/main/java/org/pptx4j/samples/CreateHelloWorld.java`:
```java
// Where will we save our new .ppxt?
String outputfilepath = System.getProperty("user.dir") + "/export/pptx-test.pptx";

// Looks like trying to create a package triggers this error :(
PresentationMLPackage presentationMLPackage = PresentationMLPackage.createPackage();
``` 

I tried older versions and I can also confirm that this behavior happens v8.2.1+. However, version 8.2.0 works without any errors.

My Environment is:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
-------------------------------------
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```
Any help to solve this problem would be appreciated.

Cheers.

**Comment by plutext** [comment]
Thanks for this.  Turns out it was broken by https://github.com/plutext/docx4j/commit/36c3787d1d858728dc48ffe8af2a59e6bdf8230c#diff-36e280088288cc67c8ef1638f8a9b9b35f9021faffd8b3ce044126c5412bed42L533
