### ISSUE TITLE
PhysicalFonts - can't read TTF

### ISSUE THREAD

**Issue by plutext** [plutext/docx4j#427]
Three different issues:-

08:07:29.664 [main] DEBUG o.d.f.f.f.autodetect.FontInfoFinder 273 - 2261
java.lang.ArrayIndexOutOfBoundsException: 2261
	at org.docx4j.fonts.fop.fonts.truetype.TTFFile.readPostScript(TTFFile.java:1038)
	at org.docx4j.fonts.fop.fonts.truetype.TTFFile.readFont(TTFFile.java:552)
	at org.docx4j.fonts.fop.fonts.truetype.TTFFontLoader.read(TTFFontLoader.java:104)
	at org.docx4j.fonts.fop.fonts.truetype.TTFFontLoader.read(TTFFontLoader.java:90)
	at org.docx4j.fonts.fop.fonts.FontLoader.getFont(FontLoader.java:196)
	at org.docx4j.fonts.fop.fonts.FontLoader.loadFont(FontLoader.java:145)
	at org.docx4j.fonts.fop.fonts.FontLoader.loadFont(FontLoader.java:113)
	at org.docx4j.fonts.fop.fonts.autodetect.FontInfoFinder.find(FontInfoFinder.java:267)
	at org.docx4j.fonts.PhysicalFonts.getPhysicalFont(PhysicalFonts.java:298)
	at org.docx4j.fonts.PhysicalFonts.addPhysicalFonts(PhysicalFonts.java:236)
	at org.docx4j.fonts.PhysicalFonts.addPhysicalFont(PhysicalFonts.java:226)
	at org.docx4j.fonts.PhysicalFonts.discoverPhysicalFonts(PhysicalFonts.java:173)
	at org.docx4j.fonts.IdentityPlusMapper.<clinit>(IdentityPlusMapper.java:74)
	at org.docx4j.samples.ConvertOutPDFviaXSLFO.main(ConvertOutPDFviaXSLFO.java:146)
08:07:29.664 [main] WARN  org.docx4j.fonts.PhysicalFonts 306 - Aborting: file:/home/jharrop/.fonts/NotoSansSymbols2-Regular.ttf (can't get EmbedFontInfo[] .. try deleting fop-fonts.cache?)

08:07:29.667 [main] DEBUG o.d.f.f.f.autodetect.FontInfoFinder 273 - OpenType fonts with CFF data are not supported, yet
java.lang.UnsupportedOperationException: OpenType fonts with CFF data are not supported, yet
	at org.docx4j.fonts.fop.fonts.truetype.TTFFontLoader.buildFont(TTFFontLoader.java:118)
	at org.docx4j.fonts.fop.fonts.truetype.TTFFontLoader.read(TTFFontLoader.java:108)
	at org.docx4j.fonts.fop.fonts.truetype.TTFFontLoader.read(TTFFontLoader.java:90)
	at org.docx4j.fonts.fop.fonts.FontLoader.getFont(FontLoader.java:196)
	at org.docx4j.fonts.fop.fonts.FontLoader.loadFont(FontLoader.java:145)
	at org.docx4j.fonts.fop.fonts.FontLoader.loadFont(FontLoader.java:113)
	at org.docx4j.fonts.fop.fonts.autodetect.FontInfoFinder.find(FontInfoFinder.java:267)
	at org.docx4j.fonts.PhysicalFonts.getPhysicalFont(PhysicalFonts.java:298)
	at org.docx4j.fonts.PhysicalFonts.addPhysicalFonts(PhysicalFonts.java:236)
	at org.docx4j.fonts.PhysicalFonts.addPhysicalFont(PhysicalFonts.java:226)
	at org.docx4j.fonts.PhysicalFonts.discoverPhysicalFonts(PhysicalFonts.java:173)
	at org.docx4j.fonts.IdentityPlusMapper.<clinit>(IdentityPlusMapper.java:74)
	at org.docx4j.samples.ConvertOutPDFviaXSLFO.main(ConvertOutPDFviaXSLFO.java:146)
08:07:29.667 [main] WARN  org.docx4j.fonts.PhysicalFonts 306 - Aborting: file:/usr/share/fonts/cantarell/Cantarell-Bold.otf (can't get EmbedFontInfo[] .. try deleting fop-fonts.cache?)

08:07:29.957 [main] ERROR o.d.fonts.fop.fonts.truetype.TTFFile 180 - Dirtab loca not found.
08:07:29.957 [main] DEBUG o.d.f.f.f.autodetect.FontInfoFinder 273 - 'loca' table not found, happens when the font file doesn't contain TrueType outlines (trying to read an OpenType CFF font maybe?)
java.io.IOException: 'loca' table not found, happens when the font file doesn't contain TrueType outlines (trying to read an OpenType CFF font maybe?)
	at org.docx4j.fonts.fop.fonts.truetype.TTFFile.readIndexToLocation(TTFFile.java:1137)
	at org.docx4j.fonts.fop.fonts.truetype.TTFFile.readFont(TTFFile.java:556)
	at org.docx4j.fonts.fop.fonts.truetype.TTFFontLoader.read(TTFFontLoader.java:104)
	at org.docx4j.fonts.fop.fonts.truetype.TTFFontLoader.read(TTFFontLoader.java:90)
	at org.docx4j.fonts.fop.fonts.FontLoader.getFont(FontLoader.java:196)
	at org.docx4j.fonts.fop.fonts.FontLoader.loadFont(FontLoader.java:145)
	at org.docx4j.fonts.fop.fonts.FontLoader.loadFont(FontLoader.java:113)
	at org.docx4j.fonts.fop.fonts.autodetect.FontInfoFinder.find(FontInfoFinder.java:267)
	at org.docx4j.fonts.PhysicalFonts.getPhysicalFont(PhysicalFonts.java:298)
	at org.docx4j.fonts.PhysicalFonts.addPhysicalFonts(PhysicalFonts.java:236)
	at org.docx4j.fonts.PhysicalFonts.addPhysicalFont(PhysicalFonts.java:226)
	at org.docx4j.fonts.PhysicalFonts.discoverPhysicalFonts(PhysicalFonts.java:173)
	at org.docx4j.fonts.IdentityPlusMapper.<clinit>(IdentityPlusMapper.java:74)
	at org.docx4j.samples.ConvertOutPDFviaXSLFO.main(ConvertOutPDFviaXSLFO.java:146)
08:07:29.957 [main] WARN  org.docx4j.fonts.PhysicalFonts 306 - Aborting: file:/usr/share/fonts/noto/NotoColorEmoji.ttf (can't get EmbedFontInfo[] .. try deleting fop-fonts.cache?)

**Comment by plutext** [comment]
https://github.com/plutext/docx4j/tree/fop_fonts_2020 corrects a lot of this; will be part of docx4j 8.3
