### ISSUE TITLE
Embedded Font not found

### ISSUE THREAD

**Issue by mcaldi** [plutext/docx4j#441]
Hi, I am using docx4j 8.2.8 and I'm trying to convert a docx in a pdf file on a linux machine. The docx document has all fonts embedeed, ma randomically I'm obtaining the following error:

```
...
Caused by: org.docx4j.openpackaging.exceptions.Docx4JException: Exception writing Document to OutputStream: Failed to read font file file:/home/pippo/.docx4all/temporary%20embedded%20fonts/1617707012671-Tahoma-bold.ttf
        at org.docx4j.utils.XmlSerializerUtil.serialize(XmlSerializerUtil.java:56)
        at org.docx4j.utils.XmlSerializerUtil.serialize(XmlSerializerUtil.java:18)
        at org.docx4j.convert.out.fo.renderers.FORendererApacheFOP.render(FORendererApacheFOP.java:247)
        at org.docx4j.convert.out.fo.renderers.FORendererApacheFOP.render(FORendererApacheFOP.java:181)
        at org.docx4j.convert.out.fo.AbstractFOExporter.postprocess(AbstractFOExporter.java:168)
        at org.docx4j.convert.out.fo.AbstractFOExporter.postprocess(AbstractFOExporter.java:47)
        at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:81)
        ... 105 common frames omitted
Caused by: java.lang.RuntimeException: Failed to read font file file:/home/pippo/.docx4all/temporary%20embedded%20fonts/1617707012671-Tahoma-bold.ttf
        at org.apache.fop.fonts.LazyFont.load(LazyFont.java:132)
        at org.apache.fop.fonts.LazyFont.hasChar(LazyFont.java:179)
        at org.apache.fop.fonts.Font.hasChar(Font.java:278)
        at org.apache.fop.fonts.FontSelector.selectFontForCharacter(FontSelector.java:47)
...
```

This issue seems similar to: #289 , but is already present in the 8.2.8 version of docx4j.

In my case is very easy to replacate this issue. 1) create a new docx file and use 4 o 5 different fonts. 2) save the file embeeding fonts. 3) Try some times to generate the pdf document and the issue will occurs.
Is there a workaround for this problem?

Thanks a lot!

**Comment by ashtonbatty** [comment]
The finalizers in AbstractFontPart and/or ObfuscatedFontPart are deleting the fonts prematurely. We work around this by creating copies of these classes with the file deletions commented out, and effectively put these classes earlier in the classpath, causing them to be used in preference to the docx4j versions. To manage the temporary files we have a scheduled task that deletes old temporary fonts every minute.
Really, the fonts should be stored in somewhere (maybe FontTablePart), and deleted only at the end of the toPDF() or toFO() calls. Their filenames should also have some randomness to avoid name conflicts and race conditions (eg. use something like `Files.createTempFile(getTmpFontDir().toPath(), "docx4j-tmpfont-", fontFileName +".ttf" ).toFile()`)

**Comment by ljgp** [comment]
I have a different diagnosis, experiencing the same problem. See https://github.com/plutext/docx4j/issues/289#issuecomment-872264376

**Comment by ashtonbatty** [comment]
Hi Jason,

While trying to figure out why the fonts are being prematurely deleted, I put a breakpoint watch on AbstractExporter.export(), and got this fun stacktrace:

> Breakpoint reached at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:81)
Breakpoint reached
	**at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:81)**
	at org.docx4j.Docx4J.toFO(Docx4J.java:712)
	at org.docx4j.convert.out.fo.FOPAreaTreeHelper.getAreaTreeViaFOP(FOPAreaTreeHelper.java:191)
	at org.docx4j.convert.out.fo.LayoutMasterSetBuilder.fixExtents(LayoutMasterSetBuilder.java:138)
	at org.docx4j.convert.out.fo.LayoutMasterSetBuilder.getLayoutMasterSetFragment(LayoutMasterSetBuilder.java:97)
	at org.docx4j.convert.out.fo.XsltFOFunctions.getLayoutMasterSetFragment(XsltFOFunctions.java:84)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.docx4j.org.apache.xalan.extensions.ExtensionHandlerJavaPackage.callFunction(ExtensionHandlerJavaPackage.java:343)
	at org.docx4j.org.apache.xalan.extensions.ExtensionHandlerJavaPackage.callFunction(ExtensionHandlerJavaPackage.java:440)
	at org.docx4j.org.apache.xalan.extensions.ExtensionsTable.extFunction(ExtensionsTable.java:226)
	at org.docx4j.org.apache.xalan.transformer.TransformerImpl.extFunction(TransformerImpl.java:491)
	at org.docx4j.org.apache.xpath.functions.FuncExtFunction.execute(FuncExtFunction.java:208)
	at org.docx4j.org.apache.xpath.XPath.execute(XPath.java:342)
	at org.docx4j.org.apache.xalan.templates.ElemCopyOf.execute(ElemCopyOf.java:134)
	at org.docx4j.org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2418)
	at org.docx4j.org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)
	at org.docx4j.org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)
	at org.docx4j.org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)
	at org.docx4j.org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2418)
	at org.docx4j.org.apache.xalan.transformer.TransformerImpl.applyTemplateToNode(TransformerImpl.java:2288)
	at org.docx4j.org.apache.xalan.transformer.TransformerImpl.transformNode(TransformerImpl.java:1374)
	at org.docx4j.org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:727)
	at org.docx4j.org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1291)
	at org.docx4j.org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1269)
	at org.docx4j.XmlUtils.transform(XmlUtils.java:1421)
	at org.docx4j.XmlUtils.transform(XmlUtils.java:1252)
	at org.docx4j.convert.out.common.AbstractXsltExporterDelegate.process(AbstractXsltExporterDelegate.java:66)
	at org.docx4j.convert.out.common.AbstractWmlExporter.process(AbstractWmlExporter.java:63)
	at org.docx4j.convert.out.common.AbstractWmlExporter.process(AbstractWmlExporter.java:32)
	**at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:78)**
	at org.docx4j.Docx4J.toFO(Docx4J.java:712)
	at org.docx4j.Docx4J.toPDF(Docx4J.java:741)
	at com.example.demo.ConvertController.convertDocxToPdf(ConvertController.java:22)

I haven't had time to really delve into the code, or record and investigate all the object allocations, but my hunch is that fonts are being either deleted explicitly in the inner export() call, or deleted by finalizer after something gets reloaded and the original reference is replaced.

**Comment by arunvc** [comment]
in linux this is how the folder is listed,

```
.docx4all/temporary\ embedded\ fonts/
```
rename to a shorter folder like tmp-fonts could solve this issue

**Comment by plutext** [comment]
See now https://github.com/plutext/docx4j/commit/3b73a0e2c9cc52fcdc9b3c26c0239e81e65c3adc
