### ISSUE TITLE
FontInfoFinder.find() is looking for Embedded Fonts that aren't Thered

### ISSUE THREAD

**Issue by dyacob** [plutext/docx4j#445]
I've been making the migration away from Java 8 in my application and have come into this exception where the FontInfoFind.find method, as invoked by MainDocumentPart fontsInUse() method thinks there are embedded fonts when they are not, I've attached a test document.

**Versions:**

- Docx4J:  11.2.9
- Word:  16.48 (21041102)
- Java: openjdk 15.0.2 2021-01-19
- OS: macOS Big Sur 11.2.3

**My code fragment:**

	WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.load( file );		
	MainDocumentPart documentPart = wordMLPackage.getMainDocumentPart();
	for( String font: documentPart.fontsInUse() ) {
		fonts.add( font );
	}

[HelloWorld.docx](https://github.com/plutext/docx4j/files/6365582/HelloWorld.docx)

**The relevant part of the stacktrace:**

Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "ttcNames" is null
	at org.docx4j.fonts.IdentityPlusMapper.<clinit>(IdentityPlusMapper.java:77)
	... 46 more
**Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "ttcNames" is null
	at org.docx4j.fonts.fop.fonts.autodetect.FontInfoFinder.find(FontInfoFinder.java:234)**
	at org.docx4j.fonts.PhysicalFonts.getPhysicalFont(PhysicalFonts.java:298)
	at org.docx4j.fonts.PhysicalFonts.addPhysicalFonts(PhysicalFonts.java:236)
	at org.docx4j.fonts.PhysicalFonts.addPhysicalFont(PhysicalFonts.java:226)
	at org.docx4j.fonts.PhysicalFonts.discoverPhysicalFonts(PhysicalFonts.java:173)
	at org.docx4j.fonts.IdentityPlusMapper.<clinit>(IdentityPlusMapper.java:74)
	... 46 more

**Comment by dyacob** [comment]
I've resolved the issue, it was not quite what I thought.  No fonts were "embedded" in the sense that the font data becomes an internal part of the document.  find() appears to be scanning my installed fonts directory and loading each, it ran into a difficulty with .ttc file that was corrupt (Optima-Regular.ttc, FontLab Studio 7 also failed to load it), so the TTFFile.getTTCnames() method would fail.

Loading every user-installed font from the file system seems like overkill. I was expecting the MainDocumentPart.fontsInUse() method would scan the info from the document metadata.  There may be something here to look into as an enhancement, so I'll leave the ticket open, but feel free to close it.

The screenshot of eclipse shows the call stack entering into the find() method

<img width="1231" alt="Screen Shot 2021-05-05 at 7 26 03 AM" src="https://user-images.githubusercontent.com/8098333/117136518-7a07a680-ad76-11eb-90d3-330056e46c5f.png">
