### ISSUE TITLE
Xml tag a "lang" doesn't convert to XSL-FO (and hyphenation it`s off)

### ISSUE THREAD

**Issue by aratnitsyn** [plutext/docx4j#460]
XML tag "lang" (http://webapp.docx4java.org/OnlineDemo/ecma376/WordML/lang.html) is not converted to xsl-fo attributes (for example, for the "block" tag) and therefore hyphenation does not work.
But if I manually specify the attributes hyphenation="true", language="" and country="" in xsl-fo, hyphenation works.
Tell me how to properly configure docx4j so that hyphenation always works.

**Comment by plutext** [comment]
Please try https://github.com/plutext/docx4j/commit/094f767b9fc60a49a21774b4fb1804988fd58305

You'll need lang attribute on your runs (or rPr default) in your docx.   See http://webapp.docx4java.org/OnlineDemo/ecma376/WordML/lang.html

Currently the code uses the val attribute, not bidi or eastAsia.

Also, you'll need applicable language-specific FOP hyphenation patterns.

Any improvements, please make a PR.  thanks.

**Comment by aratnitsyn** [comment]
> 
> 
> Please try [094f767](https://github.com/plutext/docx4j/commit/094f767b9fc60a49a21774b4fb1804988fd58305)
> 
> You'll need lang attribute on your runs (or rPr default) in your docx. See http://webapp.docx4java.org/OnlineDemo/ecma376/WordML/lang.html
> 
> Currently the code uses the val attribute, not bidi or eastAsia.
> 
> Also, you'll need applicable language-specific FOP hyphenation patterns.
> 
> Any improvements, please make a PR. thanks.

Plutext, thank you very much for the code. The code works almost correctly, for example:
(check please 1.docx and 1.docx.txt - the "fop" file that was obtained after the conversion)
[1.docx](https://github.com/plutext/docx4j/files/6669261/1.docx)
[1.docx.txt](https://github.com/plutext/docx4j/files/6669269/1.docx.txt)

If you look at the English word "Individual", it will be wrapped in elements: block and inline. The inline element has the language and country attributes with the correct values (US, EN). But in the block element, the language and country attributes have the values RU, RU from docDefaults (in styles.xml file). Because of this problem, hyphenation does not work.

**Comment by plutext** [comment]
Please try https://github.com/plutext/docx4j/commit/417e307ecf171bb35e41869a3bbcb30cd6ea1e05

**Comment by Yay295** [comment]
Those two commits caused an exception for me on WildFly 24 (using docx4j 8.3.1). The top of the stack trace was just WildFly code so I left that off and started at the point I call into docx4j.

```
Caused by: org.docx4j.openpackaging.exceptions.Docx4JException: Exception exporting package
	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:108)
	at org.docx4j.Docx4J.toFO(Docx4J.java:710)
	at org.docx4j.Docx4J.toPDF(Docx4J.java:739)
	at util.PrintUtils.doMailMergeToPDF(PrintUtils.java:340)
	... 61 more
Caused by: org.docx4j.openpackaging.exceptions.Docx4JException: Exception writing Document to OutputStream: Invalid characters in hostname
	at org.docx4j.utils.XmlSerializerUtil.serialize(XmlSerializerUtil.java:56)
	at org.docx4j.utils.XmlSerializerUtil.serialize(XmlSerializerUtil.java:18)
	at org.docx4j.convert.out.fo.renderers.FORendererApacheFOP.render(FORendererApacheFOP.java:247)
	at org.docx4j.convert.out.fo.renderers.FORendererApacheFOP.render(FORendererApacheFOP.java:181)
	at org.docx4j.convert.out.fo.AbstractFOExporter.postprocess(AbstractFOExporter.java:168)
	at org.docx4j.convert.out.fo.AbstractFOExporter.postprocess(AbstractFOExporter.java:47)
	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:83)
	... 64 more
Caused by: java.lang.IllegalArgumentException: Invalid characters in hostname
	at java.net.HostPortrange.toLowerCase(HostPortrange.java:189)
	at java.net.HostPortrange.<init>(HostPortrange.java:150)
	at java.net.URLPermission$Authority.<init>(URLPermission.java:486)
	at java.net.URLPermission.parseURI(URLPermission.java:454)
	at java.net.URLPermission.init(URLPermission.java:170)
	at java.net.URLPermission.<init>(URLPermission.java:166)
	at sun.net.www.protocol.http.HttpURLConnection.URLtoSocketPermission(HttpURLConnection.java:1090)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1483)
	at java.net.URL.openStream(URL.java:1068)
	at org.apache.fop.apps.io.ResourceResolverFactory$NormalResourceResolver.getResource(ResourceResolverFactory.java:224)
	at org.apache.fop.apps.io.ResourceResolverFactory$TempAwareResourceResolver.getResource(ResourceResolverFactory.java:152)
	at org.apache.fop.apps.io.ResourceResolverFactory$DefaultResourceResolver.getResource(ResourceResolverFactory.java:121)
	at org.apache.fop.apps.io.InternalResourceResolver.getResource(InternalResourceResolver.java:92)
	at org.apache.fop.apps.io.InternalResourceResolver.getResource(InternalResourceResolver.java:78)
	at org.apache.fop.hyphenation.Hyphenator.getHyphenationTreeStream(Hyphenator.java:240)
	at org.apache.fop.hyphenation.Hyphenator.getUserHyphenationTree(Hyphenator.java:192)
	at org.apache.fop.hyphenation.Hyphenator.getHyphenationTree(Hyphenator.java:83)
	at org.apache.fop.hyphenation.Hyphenator.hyphenate(Hyphenator.java:251)
	at org.apache.fop.layoutmgr.inline.LineLayoutManager.getHyphenContext(LineLayoutManager.java:1431)
	at org.apache.fop.layoutmgr.inline.LineLayoutManager.findHyphenationPoints(LineLayoutManager.java:1332)
	at org.apache.fop.layoutmgr.inline.LineLayoutManager.findOptimalBreakingPoints(LineLayoutManager.java:864)
	at org.apache.fop.layoutmgr.inline.LineLayoutManager.createLineBreaks(LineLayoutManager.java:823)
	at org.apache.fop.layoutmgr.inline.LineLayoutManager.getNextKnuthElements(LineLayoutManager.java:640)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:290)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextChildElements(FlowLayoutManager.java:223)
	at org.apache.fop.layoutmgr.FlowLayoutManager.addChildElements(FlowLayoutManager.java:147)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextKnuthElements(FlowLayoutManager.java:116)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextKnuthElements(FlowLayoutManager.java:69)
	at org.apache.fop.layoutmgr.PageBreaker.getNextKnuthElements(PageBreaker.java:251)
	at org.apache.fop.layoutmgr.AbstractBreaker.getNextBlockList(AbstractBreaker.java:770)
	at org.apache.fop.layoutmgr.PageBreaker.getNextBlockList(PageBreaker.java:178)
	at org.apache.fop.layoutmgr.PageBreaker.getNextBlockList(PageBreaker.java:158)
	at org.apache.fop.layoutmgr.AbstractBreaker.doLayout(AbstractBreaker.java:389)
	at org.apache.fop.layoutmgr.PageBreaker.doLayout(PageBreaker.java:112)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:143)
	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:139)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at org.docx4j.org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1148)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:598)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(XMLNSDocumentScannerImpl.java:673)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(XMLDocumentFragmentScannerImpl.java:1645)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:324)
	at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:875)
	at org.apache.xerces.parsers.XML11Configuration.parse(XML11Configuration.java:798)
	at org.apache.xerces.parsers.XMLParser.parse(XMLParser.java:108)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1198)
	at __redirected.__XMLReaderFactory.parse(__XMLReaderFactory.java:140)
	at org.docx4j.org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:518)
	at org.docx4j.utils.XmlSerializerUtil.serialize(XmlSerializerUtil.java:51)
	... 70 more
```

Interestingly I also tried this code in WebSphere 8.5.5.20 and it worked without issue. After reverting the two commits mentioned above it worked in both WildFly and WebSphere.

**Comment by plutext** [comment]
I wonder what URL FOP is trying to open for that hyphenation resource?

```
at java.net.URL.openStream(URL.java:1068)
	at org.apache.fop.apps.io.ResourceResolverFactory$NormalResourceResolver.getResource(ResourceResolverFactory.java:224)
	at org.apache.fop.apps.io.ResourceResolverFactory$TempAwareResourceResolver.getResource(ResourceResolverFactory.java:152)
	at org.apache.fop.apps.io.ResourceResolverFactory$DefaultResourceResolver.getResource(ResourceResolverFactory.java:121)
	at org.apache.fop.apps.io.InternalResourceResolver.getResource(InternalResourceResolver.java:92)
	at org.apache.fop.apps.io.InternalResourceResolver.getResource(InternalResourceResolver.java:78)
	at org.apache.fop.hyphenation.Hyphenator.getHyphenationTreeStream(Hyphenator.java:240)
```

Could it be that WildFly is configured to disallow opening external URLs but that your WebSphere 8.5.5.20 allows it?

**Comment by Yay295** [comment]
I tried looking into it, but I couldn't see what URL it's trying to open. My WildFly server is more restrictive with its permissions though, so that is probably why it works on my WebSphere server.

**Comment by Yay295** [comment]
Changing `block.setAttribute("hyphenate", "true");` to `block.setAttribute("hyphenate", "false");` worked. I had to modify the XsltFOFunctions class to do this though. Is there a way to change that attribute without editing any of the docx4j code?

I also noticed though that this new code doesn't combine ligatures anymore. For example the "ﬁ" ligature is being rendered as separate characters. I'd guess this has to do with the default `lang` value.

I think the root of the problem *might* be that the default language value is now an empty string rather than not being set at all. I think this would cause the ligature change I'm seeing, and also the "Invalid characters in hostname" exception. It looks like [the language value is being used in a URL](https://github.com/apache/xmlgraphics-fop/blob/678d6c0e04fd6a5464012be0241bb771cf9bb506/fop-core/src/main/java/org/apache/fop/hyphenation/HyphenationTreeCache.java#L78), with [an extension added to the end](https://github.com/apache/xmlgraphics-fop/blob/678d6c0e04fd6a5464012be0241bb771cf9bb506/fop-core/src/main/java/org/apache/fop/hyphenation/Hyphenator.java#L186). If the language value is empty, then the URL it's trying to connect to would be just ".hyp", which isn't valid.

**Comment by plutext** [comment]
@Yay295 could you please provide a simple test docx (or docx4j code to create same) with which to explore these issues (hyphenation, ligatures).

**Comment by Yay295** [comment]
I'm getting this exception even with a document containing only a single letter. An empty document does work though, as useless as that is.

[example.docx](https://github.com/plutext/docx4j/files/8017144/example.docx)

**Comment by Yay295** [comment]
Updating to 8.3.2 didn't fix anything.

**Comment by plutext** [comment]
Commits at https://github.com/plutext/docx4j/commits/master over the last couple of days should fix this:

- new property docx4j.convert.out.fo.hyphenate must be set to true for hyphenation to occur
- baseURI can be configured at docx4j.convert.out.fop.FopConfParser.defaultBaseURI; it now defaults to the current directory (".")
- you can set your own customer resource resolver if necessary

This will be in a 8.3.3 release, expect to be made in the next day or 2.

**Comment by plutext** [comment]
See now https://www.docx4java.org/forums/docx-java-f6/docx4j-8-3-3-released-t3033.html

**Comment by Yay295** [comment]
I'm getting this exception now:

```
java.io.IOException: org.docx4j.openpackaging.exceptions.Docx4JException: Exception exporting package
    at util.LetterUtils.convertWordToPDF(LetterUtils.java:344)
    at util.LetterUtils.generatePDF(LetterUtils.java:357)
    at util.LetterUtils.generatePDF(LetterUtils.java:376)
    at util.LetterUtilsTest.testGeneratePDF2(LetterUtilsTest.java:150)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
    at java.lang.reflect.Method.invoke(Method.java:508)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.mockito.internal.junit.JUnitSessionStore$1.evaluateSafely(JUnitSessionStore.java:55)
    at org.mockito.internal.junit.JUnitSessionStore$1.evaluate(JUnitSessionStore.java:43)
    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
    at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
    at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.docx4j.openpackaging.exceptions.Docx4JException: Exception exporting package
    at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:108)
    at org.docx4j.Docx4J.toFO(Docx4J.java:710)
    at org.docx4j.Docx4J.toPDF(Docx4J.java:739)
    at util.LetterUtils.convertWordToPDF(LetterUtils.java:341)
    ... 31 more
Caused by: org.docx4j.openpackaging.exceptions.Docx4JException: You must invoke FORendererApacheFOP.getFOUserAgent
    at org.docx4j.convert.out.fo.renderers.FORendererApacheFOP.render(FORendererApacheFOP.java:124)
    at org.docx4j.convert.out.fo.AbstractFOExporter.postprocess(AbstractFOExporter.java:168)
    at org.docx4j.convert.out.fo.AbstractFOExporter.postprocess(AbstractFOExporter.java:47)
    at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:83)
    ... 34 more
```

Am I supposed to call `FORendererApacheFOP.getFOUserAgent()` myself somewhere? Previously I was just doing this:

```java
final WordprocessingMLPackage wpml = Docx4J.load(inputStream);
final Mapper fm = new MyCustomFontMapper();
wpml.setFontMapper(fm);

// mail merge and some other processing

final ByteArrayOutputStream baos = new ByteArrayOutputStream();
Docx4J.toPDF(wmlp,baos);
```

but now I get that exception.

If I do this instead:

```java
final WordprocessingMLPackage wpml = Docx4J.load(inputStream);
final Mapper fm = new MyCustomFontMapper();
wpml.setFontMapper(fm);

// mail merge and some other processing

final FOSettings fos = new FOSettings();
fos.setOpcPackage(wmlp);
final FopFactoryBuilder fopfb = FORendererApacheFOP.getFopFactoryBuilder(fos);
final FOUserAgent foua = FORendererApacheFOP.getFOUserAgent(fos,fopfb.build());

final ByteArrayOutputStream baos = new ByteArrayOutputStream();
Docx4J.toFO(fos,baos,Docx4J.FLAG_EXPORT_PREFER_XSL);
```

I don't get an exception, but the generated PDFs don't contain any custom fonts from my font mapper.

**Comment by plutext** [comment]
As per the release announcement, the config has changed.  

See https://github.com/plutext/docx4j/blob/master/docx4j-samples-docx-export-fo/src/main/java/org/docx4j/samples/ConvertOutPDFviaXSLFO.java#L194 

```
	public static FOUserAgent getFOUserAgent(FOSettings settings, FopFactory fopFactory) throws Docx4JException, FOPException {
		
		if (fopFactory==null) {
			throw new Docx4JException("FopFactory is null");
		}
		settings.getSettings().put(FOP_FACTORY, fopFactory);
		
	    FOUserAgent foUserAgent = fopFactory.newFOUserAgent();
		settings.getSettings().put(FO_USER_AGENT, foUserAgent);
		
		return foUserAgent;
	}
```

As per the example, you need to pass a FopFactory.

What does `MyCustomFontMapper` do?

**Comment by Yay295** [comment]
Why do I have to manually call `FORendererApacheFOP.getFOUserAgent()` if I don't use the response though? I don't need `FOSettings`, `FopFactory`, or `FOUserAgent`. Shouldn't `Docx4J.toPDF()` handle that automatically? Like just add
```java
final FopFactoryBuilder fopfb = FORendererApacheFOP.getFopFactoryBuilder(settings);
FORendererApacheFOP.getFOUserAgent(settings,fopfb.build());
```
right before this line https://github.com/plutext/docx4j/blob/0eec2587ab38db5265ce66c12423849c1bea2c60/docx4j-core/src/main/java/org/docx4j/Docx4J.java#L739

---

`MyCustomFontMapper` has a static block that loads the specific fonts I use using `PhysicalFonts.addPhysicalFont(uri)`, and then aliases some of them using `PhysicalFonts.put(alias,font)`. It uses the same `populateFontMappings` method as the `IdentityPlusMapper`. So it's nearly the same as the `IdentityPlusMapper`, but I tell it specifically which font files I want it to use instead of letting it look around for anything it can find.

**Comment by Yay295** [comment]
I've tried it with `IdentityPlusMapper` and with not manually setting a mapper and got the same result - no fonts are included in the PDF.

**Comment by Yay295** [comment]
I tried using a `BestMatchingMapper` and got a `NullPointerException` here: https://github.com/plutext/docx4j/blob/81179ec7d85b7ba16357b0a1087c4a3b4407b90e/docx4j-core/src/main/java/org/docx4j/fonts/fop/util/FopConfigUtil.java#L222

**Comment by plutext** [comment]
Hmmm, sorry, we didn't put the new FOP configuration stuff in the toPDF facade.  Fixed at https://github.com/plutext/docx4j/commit/64bc5be4573874ea4df8f719c7b27e8822af5412

https://github.com/plutext/docx4j/commit/61ec69d94c468eddba6fdbed10babfcb6dd00c25 fixes the NPE you reported immediately above, thanks.

I will try `IdentityPlusMapper` on a Windows machine.

**Comment by plutext** [comment]
Please try https://www.docx4java.org/forums/announces/docx4j-8-3-4-released-t3034.html

**Comment by Yay295** [comment]
My mapper and the `IdentityPlusMapper` are now working, but the `BestMatchingMapper` isn't adding any fonts to the PDF. `Docx4J.toPDF()` is working now though, the NPE is fixed, and I am able to generate PDF's in both WildFly and WebSphere again.

**Comment by plutext** [comment]
Great.  `BestMatchingMapper` works for me.  When you say it isn't adding any fonts, is the fop fontconfig empty, or can you just not see the fonts you expect?  If you want to pursue this, please open a new issue.

**Comment by Yay295** [comment]
I didn't check the fontconfig; I just saw the PDF file it creates doesn't have any fonts bundled with it like it does when I use a different mapper. It's not an issue for me though since I am using a different mapper. Thanks for working on this.
