### ISSUE TITLE
simple example with error: org.docx4j.openpackaging.exceptions.Docx4JException: Error marshalling Content_Types 

### ISSUE THREAD

**Issue by yangxiaomin08** [plutext/docx4j#461]
Dear,

I'm comparing between POI and doc4j, but I got stuck for a basic example doc4j provided.
I also try to add the dependencies in my pom.xml. (Referring to this [post](https://www.docx4java.org/forums/docx-java-f6/moxy-t1242.html#p5598) ).

I still got this error below, can anyone give me a hand? thanks a lot.

org.docx4j.openpackaging.exceptions.Docx4JException: Error marshalling Content_Types 
	at org.docx4j.openpackaging.io3.stores.ZipPartStore.saveContentTypes(ZipPartStore.java:315)
	at org.docx4j.openpackaging.io3.Save.save(Save.java:177)
	at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:788)
	at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:718)
	at org.docx4j.Docx4J.save(Docx4J.java:295)
	at org.docx4j.toc.TocGenerator.getPageNumbersMapViaService(TocGenerator.java:676)
	at org.docx4j.toc.TocGenerator.getPageNumbersMap(TocGenerator.java:658)
	at org.docx4j.toc.TocGenerator.populateToc(TocGenerator.java:402)
	at org.docx4j.toc.TocGenerator.generateToc(TocGenerator.java:266)
	at org.docx4j.toc.TocGenerator.generateToc(TocGenerator.java:234)
	at org.docx4j.toc.TocGenerator.generateToc(TocGenerator.java:194)
	at org.docx4j.samples.TocAdd.main(TocAdd.java:97)
Caused by: javax.xml.bind.JAXBException: Can't create org.docx4j.jaxb.moxy.NamespacePrefixMapper

my pom.xml file:
    <dependency>
        <groupId>org.docx4j</groupId>
        <artifactId>docx4j-core</artifactId>
        <version>8.3.0</version>
    </dependency>
    <dependency>
        <groupId>org.docx4j</groupId>
        <artifactId>docx4j-MOXy-JAXBContext</artifactId>
        <version>6.0.0</version>
    </dependency>
    <dependency>
        <groupId>org.eclipse.persistence</groupId>
        <artifactId>org.eclipse.persistence.moxy</artifactId>
        <version>2.5.1</version>
    </dependency>

**Comment by plutext** [comment]
Don't mix docx4j versions 8.3.0 and 6.0.0
