### ISSUE TITLE
No Docx4jUnmarshallerListener where pre-processing

### ISSUE THREAD

**Issue by plutext** [plutext/docx4j#474]
since can't set it on xslt.

This means that mcChoiceNamespaces won't be gathered, so they won't be forced to be declared top-level

If they aren't declared top-level, Word can't open the docx.

So avoid pre-processing if you can.

**Comment by plutext** [comment]
or when using binder, since binder doesn't support listener

**Comment by plutext** [comment]
XSLT portion worked around at 7c6332dc by using DOMResult instead of JAXB Result

**Comment by plutext** [comment]
0:02:47.500 [main] ERROR org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware -- Unmarshalling via binder, couldn't set Docx4jUnmarshallerListener. McChoiceNamespace declarations will be affected.
10:02:47.500 [main] ERROR org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware -- Couldn't set Docx4jUnmarshallerListener on binder
java.lang.reflect.InaccessibleObjectException: Unable to make private org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl org.glassfish.jaxb.runtime.v2.runtime.BinderImpl.getUnmarshaller() accessible: module org.glassfish.jaxb.runtime does not "opens org.glassfish.jaxb.runtime.v2.runtime" to module org.docx4j.JAXB_ReferenceImpl
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:200)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:194)
        at org.docx4j.JAXB_ReferenceImpl@11.5.2/org.docx4j.jaxb.ri.BinderListener.setListener(BinderListener.java:23)
        at org.docx4j.core@11.5.2/org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware.unmarshal(JaxbXmlPartXPathAware.java:710)
        at org.docx4j.core@11.5.2/org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware.getBinder(JaxbXmlPartXPathAware.java:144)
        at org.docx4j.core@11.5.2/org.docx4j.openpackaging.parts.JaxbXmlPartXPathAware.getJAXBNodesViaXPath(JaxbXmlPartXPathAware.java:209)
