### ISSUE TITLE
NullPointerException in FopConfigUtil.declareRendererFonts() after upgrade to docx4j 8.3.3

### ISSUE THREAD

**Issue by bobpancras** [plutext/docx4j#499]
**Problem:**
I just upgraded docx4j from 8.3.1 to 8.3.3. Converting a docx file to pdf via FO works fine on a Windows machine, but on a Linux machine I get the following NullPointerException:
java.lang.NullPointerException: null
        at org.docx4j.fonts.fop.util.FopConfigUtil.declareRendererFonts(FopConfigUtil.java:222) ~[docx4j-core-8.3.3.jar:?]
        at org.docx4j.fonts.fop.util.FopConfigUtil.createConfigurationObject(FopConfigUtil.java:122) ~[docx4j-core-8.3.3.jar:?]
        at org.docx4j.convert.out.FOSettings.setOpcPackage(FOSettings.java:82) ~[docx4j-core-8.3.3.jar:?]

**Analysis:**
In the logging I see the following:
docx4j 8.3.1:
WARN FopConfigUtil - Document font Arial is not mapped to a physical font!
WARN FopConfigUtil - Document font Times New Roman is not mapped to a physical font!

docx4j 8.3.3:
WARN  FopConfigUtil - Document font Arial is not mapped to a physical font!
java.lang.NullPointerException: null
        at org.docx4j.fonts.fop.util.FopConfigUtil.declareRendererFonts(FopConfigUtil.java:222) ~[docx4j-core-8.3.3.jar:?]
        at org.docx4j.fonts.fop.util.FopConfigUtil.createConfigurationObject(FopConfigUtil.java:122) ~[docx4j-core-8.3.3.jar:?]
        at org.docx4j.convert.out.FOSettings.setOpcPackage(FOSettings.java:82) ~[docx4j-core-8.3.3.jar:?]

**Possible solution:**
In FopConfigUtil.declareRendererFonts() change the call of

```
addVariations(fontMapper, rendererFonts, fontName, pf, 
	pf.getEmbedFontInfo().getSubFontName());
```
to

```
addVariations(fontMapper, rendererFonts, fontName, pf, 
	pf != null ? pf.getEmbedFontInfo().getSubFontName() : null);
```

**Comment by plutext** [comment]
FIxed at https://github.com/plutext/docx4j/commit/61ec69d94c468eddba6fdbed10babfcb6dd00c25

Please try v8.3.4, as to which see https://www.docx4java.org/forums/announces/docx4j-8-3-4-released-t3034.html

**Comment by bobpancras** [comment]
Thanks for fixing that quick @plutext!
The fix is working for us.
