### ISSUE TITLE
HTML to DOCX conversion fails if void html tags are present

### ISSUE THREAD

**Issue by Rade96** [plutext/docx4j#508]
In case when my html contains tag `<br>`, library does not recognize that it is a void html tag, and throws an error due to the missing closing tag.

The exception thrown is:
``` java
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 323; The element type "br" must be terminated by the matching end-tag "</br>".
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at __redirected.__XMLReaderFactory.parse(__XMLReaderFactory.java:201)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
```

Code used to convert html to docx:

``` java
public byte[] convertHtmlToDocx(String html) throws Docx4JException {

		WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.createPackage();

		XHTMLImporterImpl XHTMLImporter = new XHTMLImporterImpl(wordMLPackage);

		InputStream inputStream = getClass().getClassLoader().getResourceAsStream("/oj.css");
		String css = "";

		try {
			css = String.join("", IOUtils.readLines(inputStream, StandardCharsets.UTF_8));
		} catch (IOException e) {
			e.printStackTrace();
		}

		wordMLPackage.getMainDocumentPart().getStyleDefinitionsPart().setCss(css);
		wordMLPackage.getMainDocumentPart().getContent().addAll(XHTMLImporter.convert(html, null));

		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		wordMLPackage.save(baos);
		return baos.toByteArray();
	}
```

Workaround is to replace all the occurances of `<br>` with `<br></br>` (does not work with `<br />`).

**Comment by plutext** [comment]
All input must be well formed XML.
