### ISSUE TITLE
Unable to use CTHyperlinkColor

### ISSUE THREAD

**Issue by LordRaptor** [plutext/docx4j#532]
I am trying to set the hyperlink color of a link using the following code

```java   
        CTHyperlinkColor ctHyperlinkColor = new ObjectFactory().createCTHyperlinkColor();
        ctHyperlinkColor.setVal(STHyperlinkColor.TX);

        CTOfficeArtExtension ctOfficeArtExtension = new CTOfficeArtExtension();
        ctHyperlinkColor.setParent(ctOfficeArtExtension);
        ctOfficeArtExtension.setAny(ctHyperlinkColor);
        ctOfficeArtExtension.setUri("{A12FA001-AC4F-418D-AE19-62706E023703}");

        CTOfficeArtExtensionList ctOfficeArtExtensionList = new CTOfficeArtExtensionList();
        ctOfficeArtExtensionList.getExt()
            .add(ctOfficeArtExtension);
        hlinkClick.setExtLst(ctOfficeArtExtensionList);
```
However trying to save the package, I get the following exception (cut out most of the stacktrace):
`javax.xml.bind.JAXBException: class org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.CTHyperlinkColor nor any of its super class is known to this context.`

I'm using version `org.docx4j:docx4j-JAXB-Internal:8.1.4` (upgrading will be a larger project, I need to be sure that would fix the issue before I can approach an upgrade).

Am I using the CTHyperlinkColor wrong? I've been trying to replicate what I saw in a PPT test file I created.

**Comment by plutext** [comment]
Try wrapping it in a JAXBElement.  From the ObjectFactory class:

```
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/office/drawing/2018/hyperlinkcolor", name = "hlinkClr")
    public JAXBElement<CTHyperlinkColor> createHlinkClr(CTHyperlinkColor value) {
        return new JAXBElement<CTHyperlinkColor>(_HlinkClr_QNAME, CTHyperlinkColor.class, null, value);
    }
```

Are you sure org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.CTHyperlinkColor is the object you want?  If you need more help, please attach simple sample pptx.

**Comment by LordRaptor** [comment]
I've tried wrapping it as you suggested, it did not make a difference (which is surprising, I was expecting the stacktrace to change at least).


Here is an example file
[CT_HLinkColor Example.pptx](https://github.com/plutext/docx4j/files/10371599/CT_HLinkColor.Example.pptx)

Stacktrace (cut out the part in my codebase)
```stacktrace
Caused by: org.docx4j.openpackaging.exceptions.Docx4JException: Failed to add parts from relationships of /
        at org.docx4j.openpackaging.io3.Save.addPartsFromRelationships(Save.java:404)
        at org.docx4j.openpackaging.io3.Save.save(Save.java:193)
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:795)
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:718)
        at org.docx4j.openpackaging.packages.OpcPackage.save(OpcPackage.java:706)
        at com.trendiction.tw.powerpoint.PowerPointUtils.buildPresentation(PowerPointUtils.java:41)
        at framework.tw.renders.generic.documents.AbstractPPTDocument.publishContent(AbstractPPTDocument.java:140)
        ... 28 more
Caused by: org.docx4j.openpackaging.exceptions.Docx4JException: Failed to add parts from relationships of /ppt/presentation.xml
        at org.docx4j.openpackaging.io3.Save.addPartsFromRelationships(Save.java:404)
        at org.docx4j.openpackaging.io3.Save.savePart(Save.java:456)
        at org.docx4j.openpackaging.io3.Save.addPartsFromRelationships(Save.java:399)
        ... 34 more
Caused by: org.docx4j.openpackaging.exceptions.Docx4JException: Problem saving part /ppt/slides/slide1.xml
        at org.docx4j.openpackaging.io3.Save.saveRawXmlPart(Save.java:318)
        at org.docx4j.openpackaging.io3.Save.savePart(Save.java:436)
        at org.docx4j.openpackaging.io3.Save.addPartsFromRelationships(Save.java:399)
        ... 36 more
Caused by: org.docx4j.openpackaging.exceptions.Docx4JException: Error marshalling JaxbXmlPart /ppt/slides/slide1.xml
        at org.docx4j.openpackaging.io3.stores.ZipPartStore.saveJaxbXmlPart(ZipPartStore.java:365)
        at org.docx4j.openpackaging.io3.Save.saveRawXmlPart(Save.java:289)
        ... 38 more
Caused by: javax.xml.bind.JAXBException
 - with linked exception:
[javax.xml.bind.MarshalException
 - with linked exception:
[com.sun.istack.internal.SAXException2: org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.CTHyperlinkColor is not known to this context
javax.xml.bind.JAXBException: org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.CTHyperlinkColor is not known to this context]]
        at org.docx4j.openpackaging.parts.JaxbXmlPart.marshal(JaxbXmlPart.java:923)
        at org.docx4j.openpackaging.parts.JaxbXmlPart.marshal(JaxbXmlPart.java:738)
        at org.docx4j.openpackaging.io3.stores.ZipPartStore.saveJaxbXmlPart(ZipPartStore.java:308)
        ... 39 more
Caused by: javax.xml.bind.MarshalException
 - with linked exception:
[com.sun.istack.internal.SAXException2: org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.CTHyperlinkColor is not known to this context
javax.xml.bind.JAXBException: org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.CTHyperlinkColor is not known to this context]
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:311)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:236)
        at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:95)
        at org.docx4j.openpackaging.parts.JaxbXmlPart.marshal(JaxbXmlPart.java:870)
        ... 41 more
Caused by: com.sun.istack.internal.SAXException2: org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.CTHyperlinkColor is not known to this context
javax.xml.bind.JAXBException: org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.CTHyperlinkColor is not known to this context
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.reportError(XMLSerializer.java:232)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.reportError(XMLSerializer.java:247)
        at com.sun.xml.internal.bind.v2.runtime.ElementBeanInfoImpl$1.serializeBody(ElementBeanInfoImpl.java:132)
        at com.sun.xml.internal.bind.v2.runtime.ElementBeanInfoImpl$1.serializeBody(ElementBeanInfoImpl.java:115)
        at com.sun.xml.internal.bind.v2.runtime.ElementBeanInfoImpl.serializeBody(ElementBeanInfoImpl.java:317)
        at com.sun.xml.internal.bind.v2.runtime.ElementBeanInfoImpl.serializeRoot(ElementBeanInfoImpl.java:324)
        at com.sun.xml.internal.bind.v2.runtime.ElementBeanInfoImpl.serializeRoot(ElementBeanInfoImpl.java:60)
        at com.sun.xml.internal.bind.v2.runtime.property.SingleReferenceNodeProperty.serializeBody(SingleReferenceNodeProperty.java:100)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayElementNodeProperty.serializeItem(ArrayElementNodeProperty.java:54)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayElementProperty.serializeListBody(ArrayElementProperty.java:157)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayERProperty.serializeBody(ArrayERProperty.java:144)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.SingleElementNodeProperty.serializeBody(SingleElementNodeProperty.java:143)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.SingleElementNodeProperty.serializeBody(SingleElementNodeProperty.java:143)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.SingleElementNodeProperty.serializeBody(SingleElementNodeProperty.java:143)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayElementNodeProperty.serializeItem(ArrayElementNodeProperty.java:54)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayElementProperty.serializeListBody(ArrayElementProperty.java:157)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayERProperty.serializeBody(ArrayERProperty.java:144)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayElementNodeProperty.serializeItem(ArrayElementNodeProperty.java:54)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayElementProperty.serializeListBody(ArrayElementProperty.java:157)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayERProperty.serializeBody(ArrayERProperty.java:144)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.SingleElementNodeProperty.serializeBody(SingleElementNodeProperty.java:143)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayElementNodeProperty.serializeItem(ArrayElementNodeProperty.java:54)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayElementProperty.serializeListBody(ArrayElementProperty.java:157)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayERProperty.serializeBody(ArrayERProperty.java:144)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.SingleElementNodeProperty.serializeBody(SingleElementNodeProperty.java:143)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.SingleElementNodeProperty.serializeBody(SingleElementNodeProperty.java:143)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsSoleContent(XMLSerializer.java:578)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeRoot(ClassBeanInfoImpl.java:326)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:479)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:308)
        ... 44 more
Caused by: javax.xml.bind.JAXBException: org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.CTHyperlinkColor is not known to this context
        at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getBeanInfo(JAXBContextImpl.java:598)
        at com.sun.xml.internal.bind.v2.runtime.ElementBeanInfoImpl$1.serializeBody(ElementBeanInfoImpl.java:129)
        ... 92 more
````

**Comment by plutext** [comment]
Try the following...

```
import org.docx4j.XmlUtils;
import org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.CTHyperlinkColor;
import org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.STHyperlinkColor;
import org.docx4j.dml.CTHyperlink;
import org.docx4j.dml.CTOfficeArtExtension;
import org.docx4j.dml.CTOfficeArtExtensionList;
import org.docx4j.dml.CTRegularTextRun;
import org.docx4j.dml.CTTextBody;
import org.docx4j.dml.CTTextCharacterProperties;
import org.docx4j.dml.CTTextParagraph;
import org.docx4j.jaxb.Context;

public class tmpHyperlinkColor {

	public static void main(String[] args) {

		org.docx4j.dml.ObjectFactory dmlObjectFactory = new org.docx4j.dml.ObjectFactory();

		CTTextBody textbody = dmlObjectFactory.createCTTextBody(); 
		    // Create object for p
		    CTTextParagraph textparagraph = dmlObjectFactory.createCTTextParagraph(); 
		    textbody.getP().add( textparagraph); 

		        CTRegularTextRun regulartextrun = dmlObjectFactory.createCTRegularTextRun(); 
		        textparagraph.getEGTextRun().add( regulartextrun); 
		            // Create object for rPr
		            CTTextCharacterProperties textcharacterproperties = dmlObjectFactory.createCTTextCharacterProperties(); 
		            regulartextrun.setRPr(textcharacterproperties); 
		                // Create object for hlinkClick
		                CTHyperlink hyperlink = dmlObjectFactory.createCTHyperlink(); 
		                textcharacterproperties.setHlinkClick(hyperlink); 
		                    hyperlink.setAction( ""); 
		                    hyperlink.setTgtFrame( ""); 
		                    hyperlink.setTooltip( ""); 
		                    // Create object for extLst
		                    CTOfficeArtExtensionList officeartextensionlist = dmlObjectFactory.createCTOfficeArtExtensionList(); 
		                    hyperlink.setExtLst(officeartextensionlist); 
		                    
		                    CTOfficeArtExtension officeArtExtension = dmlObjectFactory.createCTOfficeArtExtension();
		                    officeArtExtension.setUri("TODO://");
		                    officeartextensionlist.getExt().add(officeArtExtension);
		                    
		                    CTHyperlinkColor ctHyperlinkColor = new org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.ObjectFactory().createCTHyperlinkColor();
		                    ctHyperlinkColor.setVal(STHyperlinkColor.TX);

		                    Object wrapped = new org.docx4j.com.microsoft.schemas.office.drawing.x2018.hyperlinkcolor.ObjectFactory().createHlinkClr(ctHyperlinkColor);
		                    
		                    officeArtExtension.setAny(wrapped);
		                    
		                    hyperlink.setInvalidUrl( ""); 
		                    hyperlink.setId( "rId2"); 

		  // What output?
		  System.out.println(XmlUtils.marshaltoString(textbody, true, true, Context.jc, "foo", "bar", textbody.getClass(), null));
		}
}
```

**Comment by plutext** [comment]
I get 

```
<ns70:bar xmlns:cppr="http://schemas.microsoft.com/office/2006/coverPageProps" xmlns:dgm1611="http://schemas.microsoft.com/office/drawing/2016/11/diagram" xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" xmlns:wp15="http://schemas.microsoft.com/office/word/2012/wordprocessingDrawing" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture" xmlns:a1611="http://schemas.microsoft.com/office/drawing/2016/11/main" xmlns:a16svg="http://schemas.microsoft.com/office/drawing/2016/SVG/main" xmlns:am3d="http://schemas.microsoft.com/office/drawing/2017/model3d" xmlns:pvml="urn:schemas-microsoft-com:office:powerpoint" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:dgm1612="http://schemas.microsoft.com/office/drawing/2016/12/diagram" xmlns:comp="http://schemas.openxmlformats.org/drawingml/2006/compatibility" xmlns:xvml="urn:schemas-microsoft-com:office:excel" xmlns:c173="http://schemas.microsoft.com/office/drawing/2017/03/chart" xmlns:anam3d="http://schemas.microsoft.com/office/drawing/2018/animation/model3d" xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:adec="http://schemas.microsoft.com/office/drawing/2017/decorative" xmlns:oda="http://opendope.org/answers" xmlns:a18hc="http://schemas.microsoft.com/office/drawing/2018/hyperlinkcolor" xmlns:odc="http://opendope.org/conditions" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:cdr="http://schemas.openxmlformats.org/drawingml/2006/chartDrawing" xmlns:odi="http://opendope.org/components" xmlns:msink="http://schemas.microsoft.com/ink/2010/main" xmlns:cdr14="http://schemas.microsoft.com/office/drawing/2010/chartDrawing" xmlns:iact="http://schemas.microsoft.com/office/powerpoint/2014/inkAction" xmlns:an18="http://schemas.microsoft.com/office/drawing/2018/animation" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" xmlns:odq="http://opendope.org/questions" xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns:dsp="http://schemas.microsoft.com/office/drawing/2008/diagram" xmlns:odx="http://opendope.org/xpaths" xmlns:a15="http://schemas.microsoft.com/office/drawing/2012/main" xmlns:a14="http://schemas.microsoft.com/office/drawing/2010/main" xmlns:c15="http://schemas.microsoft.com/office/drawing/2012/chart" xmlns:a13cmd="http://schemas.microsoft.com/office/drawing/2013/main/command" xmlns:c14="http://schemas.microsoft.com/office/drawing/2007/8/2/chart" xmlns:a16="http://schemas.microsoft.com/office/drawing/2014/main" xmlns:odgm="http://opendope.org/SmartArt/DataHierarchy" xmlns:c16="http://schemas.microsoft.com/office/drawing/2014/chart" xmlns:dgm="http://schemas.openxmlformats.org/drawingml/2006/diagram" xmlns:thm15="http://schemas.microsoft.com/office/thememl/2012/main" xmlns:we="http://schemas.microsoft.com/office/webextensions/webextension/2010/11" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:ns39="http://www.w3.org/2003/InkML" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:sl="http://schemas.openxmlformats.org/schemaLibrary/2006/main" xmlns:ns38="http://www.w3.org/1998/Math/MathML" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:dgm14="http://schemas.microsoft.com/office/drawing/2010/diagram" xmlns:c16ac="http://schemas.microsoft.com/office/drawing/2014/chart/ac" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:b="http://schemas.openxmlformats.org/officeDocument/2006/bibliography" xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:ns70="foo" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:cs="http://schemas.microsoft.com/office/drawing/2012/chartStyle" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:cx="http://schemas.microsoft.com/office/drawing/2014/chartex" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:pic14="http://schemas.microsoft.com/office/drawing/2010/picture" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:lc="http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas" xmlns:wetp="http://schemas.microsoft.com/office/webextensions/taskpanes/2010/11">
    <a:p>
        <a:r>
            <a:rPr>
                <a:hlinkClick r:id="rId2" invalidUrl="" action="" tgtFrame="" tooltip="">
                    <a:extLst>
                        <a:ext uri="TODO://">
                            <a18hc:hlinkClr val="tx"/>
                        </a:ext>
                    </a:extLst>
                </a:hlinkClick>
            </a:rPr>
        </a:r>
    </a:p>
</ns70:bar>
```

Ignore the bar element; that's contrived.

**Comment by LordRaptor** [comment]
Running your main method, I get the same output.
I've tried to make sure I do the exact same operations and order in my own code, with the following results:

- If I add the line for printing the xml onto the console to my own code, it does print it and it looks correct (similar to the test output)
- I still get the same stacktrace when trying to save the document using `org.docx4j.openpackaging.packages.OpcPackage#save(java.io.OutputStream)`, so saving using the `Docx4J.FLAG_SAVE_ZIP_FILE` flag.

Maybe it's how I create the `PresentationMLPackage`, which is done using `org.docx4j.openpackaging.packages.PresentationMLPackage#load(java.io.InputStream)` from a stored PPTX file. All the rest works fine though, I'm creating quite complex presentation without any issue

**Comment by plutext** [comment]
Seems like support for namespace xmlns:a18hc="http://schemas.microsoft.com/office/drawing/2018/hyperlinkcolor" has been in place since prior to Jan 2019: 
 https://github.com/plutext/docx4j/blob/a440fc994771f87a66c1186134e990c646661e13/docx4j-core/src/main/java/org/docx4j/jaxb/NamespacePrefixMappings.java

Nevertheless, try a test case in a current or recent release?  (11.4.8 or 8.3.7)

**Comment by LordRaptor** [comment]
Unfortunately using version docx4j-JAXB-Internal:8.3.8 did not work, I'm beginning to wonder if I have some other library in my dependencies that is interferring with this. Would you be able to give me a hint as to where I would start with debugging this issue? Any help would be appreciated

**Comment by plutext** [comment]
I see the issue now.  The reason the docx4j sample works is because the relevant objects are in Context.jc, which is the context used for docx files.

pptx4j however uses org.pptx4j.jaxb.Context.jcPML.  So the relevant packages need to be added at https://github.com/plutext/docx4j/blob/VERSION_11_4_8/docx4j-core/src/main/java/org/pptx4j/jaxb/Context.java#L62

I will look to do this later this week.

**Comment by LordRaptor** [comment]
Awesome thanks

**Comment by plutext** [comment]
Fixed in the releases at https://www.docx4java.org/forums/announces/docx4j-11-4-9-and-8-3-9-released-t3081.html

You can see the fix at https://github.com/plutext/docx4j/commit/ae46b43f64b2f7e65074087575e6eef07d2c6667
