### ISSUE TITLE
"Severe ... risk to XXE attacks" error when calling XHTMLImporterImpl.convert

### ISSUE THREAD

**Issue by florinco** [plutext/docx4j#551]
When calling the method `org.docx4j.convert.in.xhtml.XHTMLImporterImpl.convert` I can see on the console 
_com.openhtmltopdf.load SEVERE:: Unable to disable XML External Entities, which might put you at risk to XXE attacks_

I tried to get rid of this warning trying to disable this feature by replacing the TransformerFactory but found out that this is not possible being forced to used `org.docx4j.org.apache.xalan.processor.TransformerFactoryImpl` 
that does not support e.g. feature 
`XMLConstants.ACCESS_EXTERNAL_DTD` 
called by 
`com.openhtmltopdf.resource.XMLResource.XMLResourceBuilder#setTranformerFactorySecurityFeatures`

Some logs:
_2023-07-26T09:34:37,670 WARN  [main] (XmlUtils.java:214) .§> actual SAXParserFactory: org.apache.xerces.jaxp.SAXParserFactoryImpl`
2023-07-26T09:34:37,670 WARN  [main] (XmlUtils.java:269) .§> actual DocumentBuilderFactory: 
org.apache.xerces.jaxp.DocumentBuilderFactoryImpl
...
com.openhtmltopdf.load INFO:: SAX XMLReader in use (parser): org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser
com.openhtmltopdf.load INFO:: SAX XMLReader in use (parser): org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser
com.openhtmltopdf.load WARNING:: Could not set XML/SAX feature. This may be a security issue if using untrusted XML. Feature: http://javax.xml.XMLConstants/property/accessExternalDTD ->  => java.lang.IllegalArgumentException:: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
com.openhtmltopdf.load WARNING:: Could not set XML/SAX feature. This may be a security issue if using untrusted XML. Feature: http://javax.xml.XMLConstants/property/accessExternalStylesheet ->  => java.lang.IllegalArgumentException:: Not supported: http://javax.xml.XMLConstants/property/accessExternalStylesheet
com.openhtmltopdf.load SEVERE:: Unable to disable XML External Entities, which might put you at risk to XXE attacks_

Note: I tried also using another SAXParserFactory SAXReader but this is not relevant for the TransformerFactory

My stacktrace:
 _at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.setTranformerFactorySecurityFeatures(XMLResource.java:185)
  at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:242)
  at com.openhtmltopdf.resource.XMLResource$XMLResourceBuilder.access$100(XMLResource.java:145)
  at com.openhtmltopdf.resource.XMLResource.load(XMLResource.java:71)
  at org.docx4j.convert.in.xhtml.XHTMLImporterImpl.convert(XHTMLImporterImpl.java:759)_

Code sample:
`WordprocessingMLPackage wordPackage = WordprocessingMLPackage.load(docxInputStream);`
`XHTMLImporterImpl xhtmlImporter = new XHTMLImporterImpl(wordPackage);`
`List<Object> htmlAsDocx = xhtmlImporter.convert(xhtml, null);`

Do I do something wrong?
We are using docx4j 11.4.8.

Thanks and I appreciate your feedback

**Comment by florinco** [comment]
Setting
```java
System.setProperty("javax.xml.transform.TransformerFactory", "com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl");
``` 
"com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl" is the default implementation used by openhtmltopdf library.
