### ISSUE TITLE
Version 11.4.8 and 11.4.9 - What would cause this ?

### ISSUE THREAD

**Issue by harry77914** [plutext/docx4j#561]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.docx4j.openpackaging.parts.WordprocessingML.ObfuscatedFontPart.extract(ObfuscatedFontPart.java:123)
	at org.docx4j.openpackaging.parts.WordprocessingML.FontTablePart.getFontFromRelationship(FontTablePart.java:150)
	at org.docx4j.openpackaging.parts.WordprocessingML.FontTablePart.processEmbeddings(FontTablePart.java:121)
	at org.docx4j.openpackaging.packages.WordprocessingMLPackage.setFontMapper(WordprocessingMLPackage.java:362)
	at org.docx4j.openpackaging.packages.WordprocessingMLPackage.setFontMapper(WordprocessingMLPackage.java:310)
	at com.veevaservices.iaas.safety.cioms.services.CIOMSGenerator.convertToPdf(CIOMSGenerator.java:144)
	at com.veevaservices.iaas.safety.cioms.services.CIOMSGenerator.generate(CIOMSGenerator.java:72)
	at com.veevaservices.TestTokenPopulator.main(TestTokenPopulator.java:43)

**Comment by plutext** [comment]
Some issue reading that ObfuscatedFontPart embedded in the docx?

Feel free to attach the docx (you can delete all the text in it before posting) and I'll take a look.

**Comment by harry77914** [comment]
[fomr.docx](https://github.com/plutext/docx4j/files/13291343/fomr.docx)

**Comment by plutext** [comment]
Unzipping your docx, font4.odttf is zero bytes.  I have added a test for this in forthcoming 11.4.10
