### ISSUE TITLE
When being used in AWS lambda environment , its unable to run and throws an exception.

### ISSUE THREAD

**Issue by harry77914** [plutext/docx4j#563]
I need to use docx4j from aws lambda function but it seems its trying to save some data/files which result in below error as the file system is read only . Is there a way to direct dox4j to use an alternative location for cache ( if thats what its trying to do ; probably through a settings in docx4j.properties) ?

=====================

java.io.FileNotFoundException: .docx4j (Read-only file system)
at org.docx4j.fonts.BestMatchingMapper.(BestMatchingMapper.java:122)
... 8 more
Caused by: org.docx4j.fonts.fop.apps.FOPException: java.io.FileNotFoundException: .docx4j (Read-only file system)
java.io.FileNotFoundException: .docx4j (Read-only file system)
at org.docx4j.fonts.fop.util.LogUtil.handleException(LogUtil.java:61)
at org.docx4j.fonts.fop.fonts.FontCache.saveTo(FontCache.java:226)
at org.docx4j.fonts.fop.fonts.FontCache.save(FontCache.java:201)
at org.docx4j.fonts.PhysicalFonts.discoverPhysicalFonts(PhysicalFonts.java:211)
at org.docx4j.fonts.BestMatchingMapper.(BestMatchingMapper.java:106)
... 8 more
Caused by: java.io.FileNotFoundException: .docx4j (Read-only file system)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(Unknown Source)
at java.base/java.io.FileOutputStream.(Unknown Source)
at java.base/java.io.FileOutputStream.(Unknown Source)
at org.docx4j.fonts.fop.fonts.FontCache.saveTo(FontCache.java:217)
... 11 more

**Comment by harry77914** [comment]
Below is the workaround . 

![image](https://github.com/plutext/docx4j/assets/128270310/a31f3844-e7b2-413c-aaf2-e2ed91c3d493)
