### ISSUE TITLE
Could not initialize class org.docx4j.fonts.IdentityPlusMapper on loading AppleSDGothicNeo.ttc font for MacOs + java 11

### ISSUE THREAD

**Issue by llmartinll** [plutext/docx4j#590]
Good day

This is the first time trying to check out and run the project.
After a cloning the project and running `mvn clean install` on
- macOs 14.5
- azul 17.0.11
- https://github.com/plutext/docx4j/tree/VERSION_11_5_1

I noticed that the `RunFontSelectorCalibriCheckBoxTest` fails

```
java.lang.NoClassDefFoundError: Could not initialize class org.docx4j.fonts.IdentityPlusMapper
	at org.docx4j.openpackaging.packages.WordprocessingMLPackage.getFontMapper(WordprocessingMLPackage.java:375)
...
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.docx4j.fonts.fop.fonts.CustomFont.getStrippedFontName()" because "customFont" is null [in thread "main"]
	at org.docx4j.fonts.IdentityPlusMapper.<clinit>(IdentityPlusMapper.java:77)
	at org.docx4j.openpackaging.packages.WordprocessingMLPackage.getFontMapper(WordprocessingMLPackage.java:375)
	at org.docx4j.fonts.RunFontSelectorCalibriCheckBoxTest.testFont(RunFontSelectorCalibriCheckBoxTest.java:64)
```

When debugging via Intellij and found out it breaks on loading in the physical font `AppleSDGothicNeo` which is included by default in mac os in `/System/Library/Fonts`

This issue might be the same issue as https://github.com/plutext/docx4j/issues/507 but there's little information there.

The test breaks on loading in `IdentityPlusMapper` , after trying to load in the `discoveryPhysicalFonts` which tries to add the font `file:/System/Library/Fonts/AppleSDGothicNeo.ttc` for which no `customFont` can be determined at https://github.com/plutext/docx4j/blob/c09797573256c0abac8529008df7336125ea5685/docx4j-core/src/main/java/org/docx4j/fonts/fop/fonts/autodetect/FontInfoFinder.java#L242
which re-sets `customFont` to `null` which causes code further down the chain to throw.

In attempt to find out why it could not load the font; I found out that it throws an IO exception at https://github.com/plutext/docx4j/blob/c09797573256c0abac8529008df7336125ea5685/docx4j-core/src/main/java/org/docx4j/fonts/fop/fonts/truetype/OFFontLoader.java#L120

`isCFF` being `false`, it will call `new TTFFile(userKerning: true, useAdvanced: false)` and throw with error message
```
'loca' table not found, happens when the font file doesn't contain TrueType outlines (trying to read an OpenType CFF font maybe?)
```

This is where I ended up.

I'm not very knowledgeable about font types but the structure of this font appears to be different than other system fonts
From what I can gather online, it's a font for the Korean language.

**Comment by plutext** [comment]
Thank you for this.

docx4j 11.5.3 upgraded to FontBox 3.  

With 11.5.3, AppleSDGothicNeo.ttc seems to work for me, in as much as the font does not cause an exception.

The following is logged:  

`10:02:23.192 [main] INFO  o.d.f.fop.fonts.truetype.OpenFont 368 - Dirtab loca not found.
`
