### ISSUE TITLE
NPE in ListLevel.java

### ISSUE THREAD

**Issue by QAQqwe** [plutext/docx4j#593]
In org.docx4j.model.listnumbering.ListLevel

```
public ListLevel(Lvl levelNode)
    {
    	this.jaxbAbstractLvl = levelNode;
    	
        this.id = levelNode.getIlvl().toString(); 
        
        counter = new Counter();

        Lvl.Start startValueNode = levelNode.getStart();
        if (startValueNode != null)
        {
        	this.startValue = startValueNode.getVal().subtract(BigInteger.ONE);
        		// Start value is one less than the user set it to,
        		// since whenever we fetch the number, we first increment it.
            counter.setCurrentValue(this.startValue);                        
        }

        Lvl.LvlText levelTextNode = levelNode.getLvlText();
        if (levelTextNode != null)
        {
            this.levelText = levelTextNode.getVal(); 
        }

        org.docx4j.wml.RFonts fontNode = null;
        if (levelNode.getRPr() != null) {
            //XmlNode fontNode = levelNode.SelectSingleNode(".//w:rFonts", nsm);
        	fontNode = levelNode.getRPr().getRFonts();
        }
        if (fontNode != null)
        {
            this.font = fontNode.getHAnsi(); //getAttributeValue(fontNode, "w:hAnsi");
        }

        //XmlNode enumTypeNode = levelNode.SelectSingleNode("w:numFmt", nsm);
        
        NumFmt enumTypeNode = levelNode.getNumFmt();
        if (enumTypeNode != null)
        {
        	this.numFmt =  enumTypeNode.getVal(); 

            // w:numFmt="bullet" indicates a bulleted list
        	this.isBullet = numFmt.equals( NumberFormat.BULLET ); 
        	
            // this.isBullet = String.Compare(type, "bullet", StringComparison.OrdinalIgnoreCase) == 0;
        }

    }

```
   
`this.id = levelNode.getIlvl().toString();` can throw  java.lang.NullPointerException

**Comment by zyplayer** [comment]
I encountered the same issue when processing a document where levelNode.getIlvl() returns null.
The current code assumes that getIlvl() always has a value, which causes an exception in this case.
A possible workaround is:

this.id = Optional.ofNullable(levelNode.getIlvl()).orElse(BigInteger.valueOf(1)).toString();

However, I am not sure whether using a default value of 1 is the correct behavior.
Could you please advise the proper way to handle missing ilvl values?


Caused by: java.lang.NullPointerException: Cannot invoke "java.math.BigInteger.toString()" because the return value of "org.docx4j.wml.Lvl.getIlvl()" is null
	at org.docx4j.model.listnumbering.ListLevel.<init>(ListLevel.java:143)
	at org.docx4j.model.listnumbering.AbstractListNumberingDefinition.readLevel(AbstractListNumberingDefinition.java:202)
	at org.docx4j.model.listnumbering.AbstractListNumberingDefinition.readListLevelsFromAbsNode(AbstractListNumberingDefinition.java:192)
	at org.docx4j.model.listnumbering.AbstractListNumberingDefinition.<init>(AbstractListNumberingDefinition.java:156)
	at org.docx4j.openpackaging.parts.WordprocessingML.NumberingDefinitionsPart.initialiseMaps(NumberingDefinitionsPart.java:154)
	at org.docx4j.openpackaging.parts.WordprocessingML.NumberingDefinitionsPart.initialiseMaps(NumberingDefinitionsPart.java:119)
	at org.docx4j.openpackaging.parts.WordprocessingML.NumberingDefinitionsPart.getInstanceListDefinitions(NumberingDefinitionsPart.java:106)
	at org.docx4j.openpackaging.parts.WordprocessingML.NumberingDefinitionsPart.getInd(NumberingDefinitionsPart.java:374)
	at org.docx4j.openpackaging.parts.WordprocessingML.NumberingDefinitionsPart.getInd(NumberingDefinitionsPart.java:366)
	at org.docx4j.model.styles.StyleUtil.apply(StyleUtil.java:1943)
	at org.docx4j.model.styles.StyleUtil.apply(StyleUtil.java:1898)
	at org.docx4j.model.PropertyResolver.applyPPr(PropertyResolver.java:915)
	at org.docx4j.model.PropertyResolver.getEffectivePPr(PropertyResolver.java:446)
	at org.docx4j.convert.out.html.ListsToContentControls.groupContent(ListsToContentControls.java:297)
	at org.docx4j.convert.out.html.ListsToContentControls.process(ListsToContentControls.java:167)
	at org.docx4j.convert.out.html.ListsToContentControls.process(ListsToContentControls.java:114)
	at org.docx4j.convert.out.common.Preprocess.process(Preprocess.java:184)
	at org.docx4j.convert.out.common.AbstractWmlExporter.preprocess(AbstractWmlExporter.java:70)
	at org.docx4j.convert.out.common.AbstractWmlExporter.preprocess(AbstractWmlExporter.java:32)
	at org.docx4j.convert.out.common.AbstractExporter.export(AbstractExporter.java:64)
	... 51 common frames omitted
